### ISSUE TITLE
HexaPDF vs Prawn

### ISSUE THREAD

**Issue by konung** [gettalong/hexapdf#10]
Not really an issue. Just a question for the author of the gem. 

 I was lead here by a post in Ruby Weekly. And I use Prawn extensively. It looks interesting, but I was wondering if you or someone who used both tools could contrast what are the advantages of using HexaPDF vs Prawn.  I was just hoping to find a clear clear of features / advantages of using this vs Prawn or something like WickedPDF ( which is wkhtmltopdf based - although the differences there are obvious)

Thank . you

**Comment by gettalong** [comment]
The main difference is that HexaPDF is a **full PDF library** in contrast to Prawn which is a library for **generating content**.

To be more specific, it is easily possible to read an existing PDF with HexaPDF and modify parts of it before writing it out again. The modifications can be to the PDF object structure like removing superfluous annotations or the the content itself.

Prawn has no such functionality. There is basic support for using a PDF as a template using the `pdf-reader` and `prawn-template` gems but support is very limited. However, Prawn has a very featureful API when it comes to creating content, for individual pages as well as across pages.

Such a functionality will be incorporated into HexaPDF in the near future. The main functionality for providing such a feature is already available in HexaPDF, see the [page canvas API](https://hexapdf.gettalong.org/api/HexaPDF/Content/Canvas.html) and the [graphics example](https://hexapdf.gettalong.org/examples/graphics.html). What's missing is automatic box and page layout so that one can say: There is a box on this page with this dimensions at this position; show this text in the box.

This is by no means an easy feat as the development of Prawn has shown but I think it is doable and using a fully-featured PDF library as backend will make some things certainly easier. I have done a [simple benchmark comparing the basic text generation facilities of HexaPDF, Prawn and reportlab](https://gist.github.com/gettalong/0d7c576064725774299cdf4d1a51d2b9) (a Python library akin to Prawn) which shows that the text generation feature of HexaPDF are already not that bad.

In addition to being usable as a library, HexaPDF also comes with a command line tool for manipulating PDFs, see the [man page for `hexapdf`](https://hexapdf.gettalong.org/documentation/hexapdf.1.html). This tool is intended to be a replacement for tools like `pdftk` and the various Poppler-based tools like `pdfinfo`, `pdfimages`, ... I have written a [blog post about HexaPDF's performance](https://gettalong.org/blog/2016/hexapdf-performance-benchmark.html) where you can find some more information.

If you want some more background information on HexaPDF, have a look at [my homepage](https://gettalong.org/posts.html) where I have written about it.

**Comment by konung** [comment]
@gettalong  Awesome. Thank you Thomas for a thorough explanation! Perhaps this should be in the README page?

**Comment by gettalong** [comment]
Done.

**Comment by rubyFeedback** [comment]
Hmm. Just commenting here, rather than creating a new issue/question. I think hexapdf versus qpdf is also an interesting example; the qpdf author is still very active. Prawn is unfortunately not that active anymore, so I think more people will switch from prawn to hexapdf in the long run. I know I may do so this year, most likely - I even have a set-time to really research hexapdf seriously, and then most likely switching (I'll retain the old prawn code in my projects, so ultimately hexapdf will become a second option, but I am pretty certain that I will switch to hexapdf as the main default rather than prawn unless there are some serious showstoppers, but I don't expect there to be any).

**Comment by gettalong** [comment]
@rubyFeedback I already have an item on my TODO list for adding some "hexapdf vs ..." pages to the HexaPDF website, so vs qpdf, vs mutool, vs cpdf (i.e. HexaPDF CLI vs other CLIs) and also HexaPDF vs Prawn vs Origami vs CombinePDF vs WickedPDF, ... Didn't yet have time to it though.

As for Prawn: There has been a flurry of activity the past few days, with one new contributor starting to contribute enhancements  (currently mainly for CI and such), myself triaging issues and creating pull requests, and the maintainer merging the PRs, looking at issues and so on. So yeah, there is generally not that much activity as with HexaPDF but Prawn is still developed. One reason, I guess, is that's already very featureful.
