### ISSUE TITLE
Memory leak when importing

### ISSUE THREAD

**Issue by benjaminwood** [gettalong/hexapdf#103]
This may be the same issue as #97, but it seemed like there may be a couple of topics being discussed there already.

We observed a consistent memory leak when importing pages into a document. It appears that `@map` in the code below retains references to both the source and destination documents.

https://github.com/gettalong/hexapdf/blob/698fe84c940490cc98b306e0166eeb8c4dcf6f70/lib/hexapdf/importer.rb#L65-L71

I believe the use of `WeakRef` is intended to ensure that this does not result in a memory leak, but it appears as though it is not working as designed/expected.

It's pretty easy to reproduce try this:

```
big_pdf = HexaPDF::Document.open(File.open('some-file.pdf'))

big_pdf.pages.each_with_index do |page, index|
  pdf_again = HexaPDF::Document.open(File.open('some-file.pdf'))
  target_pdf = HexaPDF::Document.new
  page_to_import = pdf_again.pages[index]
  target_pdf.import(page_to_import)
  pdf_again = nil
  target_pdf = nil
end

big_pdf = nil
GC.start()
```

I've explicitly set the vars to nil and manually starting garbage collection, yet `HexaPDF::Importer.instance_variable_get(:@map)` still shows references to the document. Ruby memory debugging tools/ObjectSpace confirm that `@map` is holding on to a lot of memory.

Can you reproduce this? Removing `@map`, which I understand to be a performance optimization, solves the memory leak. Though, I suspect there may be another way to fix it.

```
def self.for(source:, destination:)
  source = NullableWeakRef.new(source)
  destination = NullableWeakRef.new(destination)
  new(source: source, destination: destination)
end
```

**Comment by gettalong** [comment]
Maybe I shouldn't have made implemented importing of objects this way. The benefit of this is that if multiple objects are imported from a document, eg. multiple pages, objects that already have been imported won't be imported again. So the performance benefit is not the main concern, the memory and file size multiplication is.

The way you fixed it, is probably the best way to do this right now. Additionally, you should probably use the `HexaPDF::Importer.for` method directly instead of relying on `HexaPDF::Document#import` so as to still get the memory/file size benefits.

The `NullableWeakRef` class *should* prevent that memory problem, this is the only reason it is used. However, Ruby's GC is quite indeterminate as can be seen by the issue you referenced and [how I have to test the `NullableWeakRef` class](https://github.com/gettalong/hexapdf/blob/master/test/hexapdf/test_importer.rb#L7-L19) (btw. I got inspiration on how to do this by looking at [Ruby's own test for `WeakRef`](https://github.com/ruby/ruby/blob/master/test/test_weakref.rb#L21-L32)).

I have tried various things but the references in the map stay alive. I don't know at this point why this is happening. Maybe there is a reference from a live object to the documents stored somewhere else by HexaPDF. But this doesn't seem likely.

Will try to find out more!

**Comment by gettalong** [comment]
@benjaminwood I'm currently trying again to fix this problem for good.

Could you please try changing lines https://github.com/gettalong/hexapdf/blob/698fe84c940490cc98b306e0166eeb8c4dcf6f70/lib/hexapdf/importer.rb#L67 and https://github.com/gettalong/hexapdf/blob/698fe84c940490cc98b306e0166eeb8c4dcf6f70/lib/hexapdf/importer.rb#L70 to

~~~ ruby
@map.keep_if {|_, v| v.weakref_alive? && v.source.weakref_alive? && v.destination.weakref_alive? } 
~~~

and 

~~~ ruby
@map[[source.hash, destination.hash]] ||= NullableWeakRef.new(new(source: source, destination: destination))
~~~

and see if it helps with your issue?

Thank you!

**Comment by gettalong** [comment]
@benjaminwood After trying the changes in my last comment in more situations and thinking a bit more about it, I'm quite sure that this won't correctly fix the problem.

However, I implemented another possible solution that is now pushed to the "devel" branch. See this comment https://github.com/gettalong/hexapdf/issues/97#issuecomment-762392763 for details.

**Comment by benjaminwood** [comment]
@gettalong - thanks for following up! I can confirm that the issue is resolved with your changes on the devel branch. :rocket:

**Comment by gettalong** [comment]
@benjaminwood That's really great to hear! :+1:  Sorry it took so long to resolve this. I will make a new release in the next few days so that this can be used in production.

**Comment by gettalong** [comment]
@benjaminwood New release is out!

**Comment by benjaminwood** [comment]
Great! Thanks again.
