### ISSUE TITLE
Extract text from compressed pdfa (FlateDecode)

### ISSUE THREAD

**Issue by celsowm** [gettalong/hexapdf#107]
Hi !
For machine learning purposes (sckit-learn), I need to extract the raw text from lots of PDF files.
After searching for days and days I've found that your lib would be able to extract text from a pdf similar like [this one](https://pdfhost.io/v/54HTT2PTw_inicial_anterior.pdf).

I've tried inumerous libs in different programming languages and, it appears that your lib has a way to deal with [FlatDecode](https://hexapdf.gettalong.org/api/HexaPDF/Filter/FlateDecode/index.html).

Unfortunately, I am newbie on Ruby and I've not found on hexapdf documentation an example to how extract text.

The best thing so far I did was this:
```

require 'hexapdf'
require 'yaml'

pdf = HexaPDF::Document.open('pdfa.pdf')
pdf.pages.each {|page| 
	puts page
	puts page.to_yaml
}
```

Is it possible to achieve that?

**Comment by gettalong** [comment]
HexaPDF can extract text from a PDF file but you would need to write some code to properly lay out the extracted text since text in a PDF is inherently unstructured, i.e. just a series of characters at certain positions. For example, you would need some algorithm to determine words and text lines.

Such a functionality is not yet integrated into HexaPDF. 

Currently I would recommend to use "pdftotext" from the poppler-utils or the [pdf-reader gem](https://github.com/yob/pdf-reader/) and its "pdftext" binary.

**Comment by celsowm** [comment]
Unfortunately xpdf pdftotext is not able to extract too

**Comment by gettalong** [comment]
The reason why you can't extract any text from the linked PDF is that this seems to be a scanned document where no real optical character recognition was done. There *are* some real characters there but those can't be correctly converted to anything readable.
