### ISSUE TITLE
Could hexapdf help with anchor links with page numbers?

### ISSUE THREAD

**Issue by ticktricktrack** [gettalong/hexapdf#12]
We are building prawn based pdf documents that cat get quite long. 

I've sorted out a table of contents page that lists the page number of the following sections. It works by storing the page numbers in a hash, then creating the table of contents at the very end. So far so good. 

Linking from one page to another is doable as well. What prawn can't do is a print friendly anchor link, like `"See page 42 for more info"`. Whatever is on page 42 hasn't been created yet. 

What makes me think hexapdf could help with it is reopening and modifying existing pages. My dream would be some kind of `gsub` where I replace a placeholder reference with the actual page number after all the pages are streamed out.

I hope this makes some sense. I'm very glad there is a very active pdf tool for ruby.

**Comment by gettalong** [comment]
In theory this could work but is very hard to do in practice due to the way text works in PDF. For example, what would you put as placeholder? A number? But with how many digits? And if the number of digits were known beforehand, which placeholder number would you choose (there may be width difference between numbers with the same number of digits, e.g. 11 and 66 for proportional fonts)?

If you have worked with LaTeX you know that it has the same problem. It is solved by running the LaTeX binary two times (or sometimes even three times if new page breaks are introduced the second time). I think that this would be the only doable way to alter information like "See page 42 for more info".

Does this help?

**Comment by ticktricktrack** [comment]
Thanks for the suggestion of running two passes. I could collect the page numbers in the first pass then fill them in in the second. The design makes sure there is enough space. 

I'll play around a bit with hexapdf as well, see what we could do with it.
