### ISSUE TITLE
Validation error for (28,0): Field FontWeight does not contain an allowed value

### ISSUE THREAD

**Issue by karosk9** [gettalong/hexapdf#120]
Hello, 
I am having an issue with updating pdf due to the following error:
```
description: "Validation error for (28,0): Field FontWeight does not contain an allowed value"
klass: "HexaPDF::Error"
title: "Validation error for (28,0): Field FontWeight does not contain an allowed value"
```
I suspect it might be an issue with the non-standard FontWeight value which is 350. (Shouldn’t be 300 or 400?)

However, I also have found general information about how font weights work:  `If the font family doesn't provide the requested weight, it will use the closest available one.`

So isn’t it a HexaPDF bug?

Here is the output from the pdf FontDescriptor that seems to cause an error
```
28=>
14:25:11 web.1    |            #<HexaPDF::Type::FontDescriptor [28, 0] value={:Ascent=>1008, :CapHeight=>700, :CharSet=>"/space/period/slash/two/three/four/six/C/F/P/S/T/a/b/c/d/e/f/g/h/i/k/l/m/n/o/p/r/s/t/u/y", :Descent=>-275, :Flags=>32, :FontBBox=>#<HexaPDF::Rectangle [0, 0] value=[-223, -275, 1180, 1008]>, :FontFamily=>"Gotham Medium", :FontFile3=>#<HexaPDF::Stream [49, 0] value={:Filter=>:FlateDecode, :Length=>2307, :Subtype=>:Type1C}>, :FontName=>:"PIBMZX+Gotham-Medium", :FontStretch=>:Normal, :FontWeight=>350, :ItalicAngle=>0, :StemV=>120, :Type=>:FontDescriptor, :XHeight=>528}>,
```

**Comment by gettalong** [comment]
Thank you for reporting this issue! Before I further dive into this, could you please clarify where you read the information about using the closest available one? Because I didn't find anything in the PDF specification.

**Comment by karosk9** [comment]
I found it on this website: https://cssreference.io/property/font-weight/
however, it is related to CSS so I do not know if it applies to PDFs nor if it's a general CSS rule. Sorry, I am not very into fonts and CSS topics. I do not rule out that the problem is the pdf itself. As far as I know, for some fonts not only 100-multiplied values are correct. The question is how does it look like for this particular one and even if it's invalid - should this prevent the user from applying changes to this pdf?

**Comment by karosk9** [comment]
It happened again for another document. It seems it's not a very rare issue. It would be great to handle it, as users usually don't have any idea that their pdf is invalid and they have no chance to fix it. A workaround could be providing a more detailed error (At the moment it is "HexaPDF::Error"), so it could be caught and handled on our side.

**Comment by gettalong** [comment]
Thanks for the reference! I thought that this might be CSS related. In the PDF spec it is defined that a value like 350 is not allowed. However, it might be a solution to use the CSS approach - I will think about this a bit more.

It is generally not a good idea to capture the validation error and then go on since it might lead to further problems.

What you can do is running the validation manually using `doc.validate` method which won't throw an error. Use the information yielded in the block to decide whether you want to abort processing the PDF or go on. Then use `doc.write` with `validate: false`.

Can you provide the font file in question by running:

~~~
hexapdf inspect path_to_pdf s 49 > font_file
~~~

**Comment by karosk9** [comment]
I didn't mean to proceed with an invalid file, I agree that it can lead to further problems. I wanted to provide detailed information to the user when a particular error occurs. So if the error was something like:  `HexaPDF::Error:FontweightError` I could tell the user what exactly is wrong with his PDF. 

Please find the font file attached:
(I added txt extension just to omit github attachment format validation)

[font_file.txt](https://github.com/gettalong/hexapdf/files/5615663/font_file.txt)

**Comment by gettalong** [comment]
Thanks for the font file! Opening it with FontForge tells me that the font should have a weight of 500. So the information in the PDF is clearly wrong. What I can try adding to the validation feature is that if the font weight  is invalid, the font data is examined to see if the information can be found and if it can, the invalid data is automatically corrected.

As for one error per validation problem: This is not really feasible because 1) validation problems are not thrown as errors in HexaPDF but just yielded to the caller and 2) there are many different validation problems which would mean creating 10s of different error classes.

**Comment by karosk9** [comment]
Ok, I thought about it again and we will just give the user general information if any HexaPDF error occurs. However, if you manage to automatically fix a pdf with such an error, that would be great. I'm looking forward to any news on this :)

**Comment by gettalong** [comment]
@karosk9 I have thought about this a bit more. The field is optional according to the spec, so I think it would be better to just delete the invalid value. This should cause no harm. A PDF reader that renders characters of the font needs to read the embedded font file anyway and can retrieve the font weight information from there.

This change will be in the next release (sometime this week).
