### ISSUE TITLE
Font in fillable forms different than if filled out in Acrobat Reader

### ISSUE THREAD

**Issue by mlibby** [gettalong/hexapdf#129]
When I fill in a PDF form in Acrobat Reader by hand and save, it formats text differently than if I fill in the fields using HexaPDF (especially important in Social Security Number field, where the different font makes a difference in laying out correctly against the background image). It looks like I'm losing boldface and some sort of condensed spacing option. 

Source file with fillable form:
[f1040.pdf](https://github.com/gettalong/hexapdf/files/5940150/f1040.pdf)

Filled in by hand:
![image](https://user-images.githubusercontent.com/36049/107161259-17faf900-6961-11eb-8c46-815041b3497d.png)
[f1040_hand.pdf](https://github.com/gettalong/hexapdf/files/5940133/f1040_hand.pdf)

Filled in with HexaPDF and Ruby:
![image](https://user-images.githubusercontent.com/36049/107161242-0285cf00-6961-11eb-8174-44d6ff17bf8b.png)
[f1040_ruby.pdf](https://github.com/gettalong/hexapdf/files/5940134/f1040_ruby.pdf)

My code (just updating one field for example here):
```
        template = File.open("f1040.pdf", "rb")
        doc = HexaPDF::Document.new(io: template)
        page1 = doc.pages[0]
        widgets = page1[:Annots]&.filter { |a| a[:Subtype] == :Widget }
        form_fields = widgets.map { |w| w.form_field }
        fields = form_fields.filter { |f| f.concrete_field_type != :push_button }
        fields[8].field_value = "123456789"
        doc.write("f1040_ruby.pdf", validate: false, incremental: false, update_fields: true, optimize: false)
```

I feel like I must be missing something simple, but I've searched with Google, looked at the docs, inspected the two output PDFs in PDFXplorer and I'm not seeing whatever is going on here.

I'd appreciate any guidance you can offer. Thank you!

**Comment by gettalong** [comment]
It seems that the input PDF doesn't use one of the standard 14 PDF fonts which are usually used for interactive forms. It uses the font `/HelveticaLTStd-Bold` which needs to be available on the target system because it is also not embedded in the PDF file.

When filling out that PDF using Evince it also doesn't work:

![Screenshot_20210208_010929](https://user-images.githubusercontent.com/4104/107163606-c8d9b600-69aa-11eb-8495-693a6c34019f.png)

HexaPDF currently only supports filling out forms if they use one of the standard 14 PDF fonts. If another font is specified, HexaPDF uses the configured fallback font. So that is the reason why the font itself looks different.

I don't know why the alignment is off. This may have to do with the fact that the form is an XFA form and not an AcroForm. XFA forms are deprecated starting with PDF 2.0 and so aren't and won't be implemented in HexaPDF (besides being a proprietary format).

**Comment by mlibby** [comment]
Thank you for looking into this. I got the same result from pdftk on the commandline in WSL as well. Definitely understand why you wouldn't support a deprecated type of form!

Given that the other fields are plain text and don't seem to rely on formatting  maybe I can change the font or the size and get it to work for this one field.

Thanks for your time and for the fantastic library.

**Comment by gettalong** [comment]
@mlibby The latest version of HexaPDF now includes the possibility of an advanced handling of AcroForm fonts that are not usable by HexaPDF. You can now specify a block for the configuration option `acro_form.fallback_font` that can respond in any way it likes to the missing font. E.g. by registering a substitution font and using that. Also see the last conversion on Gitter about that: https://gitter.im/hexapdf/hexapdf
