### ISSUE TITLE
Document#validate and No object called 'Fo6S0' stored under /Font (HexaPDF::Erro

### ISSUE THREAD

**Issue by konstantin-dzreev** [gettalong/hexapdf#13]
Hi. I'm not sure if this is an expected behavior or if I'm doing things incorrectly, but I have a PDF that passes document validation, but raises an exception when I apply one of your examples to it:

```
# show_char_bboxes.rb with tiny modification:
...
doc = HexaPDF::Document.open(ARGV.shift)

# -----> my line of code
puts "valid: #{doc.validate(auto_correct: true)}"

doc.pages.each_with_index do |page, index|
  puts "Processing page #{index + 1}"
  processor = ShowTextProcessor.new(page)
    page.process_contents(processor)
end
doc.write('show_char_boxes.pdf', optimize: true)
```
it fails with
```
valid: true
Processing page 1
...
Processing page 19
/home/konstantin/.rvm/gems/ruby-2.3.1/gems/hexapdf-0.4.0/lib/hexapdf/type/resources.rb:177:in `object_getter': No object called 'Fo6S0' stored under /Font (HexaPDF::Error)
	from /home/konstantin/.rvm/gems/ruby-2.3.1/gems/hexapdf-0.4.0/lib/hexapdf/type/resources.rb:147:in `font'
	from /home/konstantin/.rvm/gems/ruby-2.3.1/gems/hexapdf-0.4.0/lib/hexapdf/content/operator.rb:766:in `invoke'
	from /home/konstantin/.rvm/gems/ruby-2.3.1/gems/hexapdf-0.4.0/lib/hexapdf/content/processor.rb:348:in `process'
	from /home/konstantin/.rvm/gems/ruby-2.3.1/gems/hexapdf-0.4.0/lib/hexapdf/content/parser.rb:165:in `parse'
	from /home/konstantin/.rvm/gems/ruby-2.3.1/gems/hexapdf-0.4.0/lib/hexapdf/content/parser.rb:153:in `parse'
	from /home/konstantin/.rvm/gems/ruby-2.3.1/gems/hexapdf-0.4.0/lib/hexapdf/type/form.rb:98:in `process_contents'
	from /home/konstantin/.rvm/gems/ruby-2.3.1/gems/hexapdf-0.4.0/lib/hexapdf/content/processor.rb:367:in `paint_xobject'
	from /home/konstantin/.rvm/gems/ruby-2.3.1/gems/hexapdf-0.4.0/lib/hexapdf/content/processor.rb:350:in `process'
	from /home/konstantin/.rvm/gems/ruby-2.3.1/gems/hexapdf-0.4.0/lib/hexapdf/content/parser.rb:165:in `parse'
	from /home/konstantin/.rvm/gems/ruby-2.3.1/gems/hexapdf-0.4.0/lib/hexapdf/content/parser.rb:153:in `parse'
	from /home/konstantin/.rvm/gems/ruby-2.3.1/gems/hexapdf-0.4.0/lib/hexapdf/type/page.rb:249:in `process_contents'
	from ../hexapdf/examples/show_char_bboxes.rb:56:in `block in <main>'
	from /home/konstantin/.rvm/gems/ruby-2.3.1/gems/hexapdf-0.4.0/lib/hexapdf/type/page_tree_node.rb:204:in `block in each_page'
	from /home/konstantin/.rvm/gems/ruby-2.3.1/gems/hexapdf-0.4.0/lib/hexapdf/type/page_tree_node.rb:201:in `each'
	from /home/konstantin/.rvm/gems/ruby-2.3.1/gems/hexapdf-0.4.0/lib/hexapdf/type/page_tree_node.rb:201:in `each_page'
	from /home/konstantin/.rvm/gems/ruby-2.3.1/gems/hexapdf-0.4.0/lib/hexapdf/document/pages.rb:112:in `each'
	from ../hexapdf/examples/show_char_bboxes.rb:52:in `each_with_index'
	from ../hexapdf/examples/show_char_bboxes.rb:52:in `<main>'
```

Is there any way to make sure the doc is valid or, better, to fix it before processing?

Thanks!

**Comment by gettalong** [comment]
HexaPDF doesn't currently implement the whole PDF spec, so the validator only checks for things it knows about. This means that if validation fails there is most certainly a problem with a PDF but if validation succeeds, there might still be problems.

As for the problem at hand: It might be a problem in the way in which HexaPDF processes Form XObjects. However, to verify this I would need the PDF to take a closer look at it. If it is too large, you could create a single page version using `hexapdf mod --pages 19 input.pdf output.pdf` since page 19 seems to produce the error. Could you provide the PDF?

**Comment by konstantin-dzreev** [comment]
Here is the link to the original file (https://drive.google.com/open?id=0B-H1DCV_nMz2VktMa1pna09kNnM), it is about 100M, sorry.
I tries to extract page 19 with the command you provided: It did extract the page but the size of the output was again 100M. I tried extracting a range of pages 19-23, and got the same result: it produced a 5 pages pdf that weighted the same 100M.

**Comment by gettalong** [comment]
Thanks for the file! I will have a look.

As for the size problem: Yes, this can happen, for example, if each page accesses a global resource dictionary. Since this resource dictionary in turn then references all objects on all pages, extracting a single page with just *its* resources is much more work (and currently not implemented in HexaPDF).

**Comment by konstantin-dzreev** [comment]
Thanks

P.S. Playing with show_char_bboxes.rb example (I replaced drawing surrounding boxes with drawing semi transparent text), I noticed another issue where ```canvas.opacity``` did not work as expected.

When I created new files using hexapdf things worked fine:

```
  # works for brand new pdf files
  @canvas.opacity(fill_alpha: 0.5, stroke_alpha: 0.5)
  @canvas.text('Hello World!', at: [50, 400])
```

But, when I opened existing files (the one that I've given you for example) the code above never drawn a transparent text, it was just as back as with opacity 1.0.
The only opacity value that made it sorta semi transparent was 0.005, but it was not easy to tune it because at 0.002 or 0.003 the text was vanishing.

```
  # a workaround for existing files
  @canvas.opacity(fill_alpha: 0.005, stroke_alpha: 0.005)
  @canvas.text('Hello World!', at: [50, 400])
```

**Comment by gettalong** [comment]
That problem with opacity probably hints at some deeper problem with the PDF itself. For example, the following script creates a PDF with some semi-transparent text and then loads the PDF and uses an overlay canvas to draw some semi-transparent text again:

~~~ ruby
require 'hexapdf'
require 'stringio'

doc = HexaPDF::Document.new
canvas = doc.pages.add(doc.add(Type: :Page, MediaBox: [0, 0, 150, 100])).canvas
canvas.font("Times", size: 20)
canvas.fill_color(0, 255, 0)
canvas.rectangle(0, 0, 50, 100).fill
canvas.fill_color(0)
canvas.opacity(fill_alpha: 0.5, stroke_alpha: 0.5)
canvas.text('Hello World!', at: [30, 40])

io = StringIO.new
doc.write(io)

doc = HexaPDF::Document.new(io: io)
canvas = doc.pages[0].canvas(type: :overlay)
canvas.font("Times", size: 20)
canvas.opacity(fill_alpha: 0.5, stroke_alpha: 0.5)
canvas.text('Hello World!', at: [20, 30])
doc.write('test.pdf')
~~~

The result looks like this:

![test.pdf](https://cloud.githubusercontent.com/assets/4104/26602326/69734d88-4583-11e7-8bd9-5678b0cfeb74.png)

As can be seen both texts have the same opacity/transparency.

**Comment by gettalong** [comment]
I had a look at the PDF you provided:

* The size problem when extracting a single page is, as I suspected, due to a global resources dictionary. This means that the resources (e.g. images) from all pages are included in the created file although they are not really used. I will put this onto my TODO list so that it will be optimized in a later version.

* The error is thrown because a form XObject (think of a stamp that can be used multiple times) used on page 19 doesn't have a resources dictionary, so the look-up of the font fails. This is allowed but strongly discouraged by the PDF spec, for versions 1.2 and later. I.e. if there *is* a resources dictionary for the form XObject, it has to be used and it is the *only* one to look at and has to contain everything; but if there isn't a resources dictionary, the one from the including page has to be used.

Therefore this is a bug and will be fixed with the next release.

As for the opacity problem: Can you open another issue for that and provide an example script that produces the invalid PDF?

**Comment by konstantin-dzreev** [comment]
sure, thank you

**Comment by gettalong** [comment]
The bug is fixed and a new HexaPDF release will be made this weekend.
