### ISSUE TITLE
Opacity is not predictable

### ISSUE THREAD

**Issue by konstantin-dzreev** [gettalong/hexapdf#14]
Here is my test code. It takes pdf as input and produces 2 pdf files: one with expected result and another with unexpected:
```
require 'hexapdf'

class ShowTextProcessor < HexaPDF::Content::Processor
  def self.hello_world(canvas)
    canvas.fill_color(0)
    canvas.stroke_color(0)
    canvas.font('Times', size: 20)

    canvas.opacity(fill_alpha: 1, stroke_alpha: 1)
    canvas.text('Banana', at: [10, 80])

    canvas.opacity(fill_alpha: 0.5, stroke_alpha: 0.5)
    canvas.text('Banana', at: [10, 70])

    canvas.opacity(fill_alpha: 0.005, stroke_alpha: 0.005)
    canvas.text('Banana', at: [10, 60])
  end

  def initialize(page)
    super()
    @canvas = page.canvas(type: :overlay)
  end

  def show_text(str)
    self.class.hello_world(@canvas)
  end
  alias :show_text_with_positioning :show_text
end

# Produces expected result
def test1(input_file)
  doc = HexaPDF::Document.open(input_file)
  ShowTextProcessor.hello_world(doc.pages.first.canvas(type: :overlay))

  doc.write(input_file+'.1.pdf')
end

# Produces unexpected result
def test2(input_file)
  doc = HexaPDF::Document.open(input_file)
  page = doc.pages[0]
  processor = ShowTextProcessor.new(page)
  page.process_contents(processor)

  doc.write(input_file+'.2.pdf')
end

input_file = ARGV.shift

test1(input_file)
test2(input_file)
```

[input1.pdf](https://drive.google.com/open?id=0B-H1DCV_nMz2OFhtY3FoWUtFdTg)
[input2.pdf](https://drive.google.com/open?id=0B-H1DCV_nMz2VmZvb3NQQUhiZnc)

Results (test1 shows expected result) :

![result1](https://cloud.githubusercontent.com/assets/52270/26647902/a84596fc-45f5-11e7-95a1-ebfa45705887.jpg)
![result2](https://cloud.githubusercontent.com/assets/52270/26648054/16161418-45f6-11e7-8537-db8b6be5d7df.jpg)

**Comment by gettalong** [comment]
Thanks for the example code, I can now reproduce the problem:

Using `input1.pdf` the content generated by `ShowTextProcessor.hello_world` is the following for test1:

~~~
 Q /F3 20 Tf
24.0 TL
BT
1 0 0 1 10 80 Tm
[(Banana)] TJ
/GS1 gs
1 0 0 1 10 70 Tm
[(Banana)] TJ
/GS2 gs
1 0 0 1 10 60 Tm
[(Banana)] TJ
ET
~~~

As expected the word "Banana" appears three times and before the last two appearances the `gs` PDF operator is invoked to set the opacity.

However, this is the content generated for test2:

~~~
 Q /F3 20 Tf
24.0 TL
BT
1 0 0 1 10 80 Tm
[(Banana)] TJ
/GS1 gs
1 0 0 1 10 70 Tm
[(Banana)] TJ
/GS2 gs
1 0 0 1 10 60 Tm
[(Banana)] TJ
/GS3 gs
1 0 0 1 10 80 Tm
[(Banana)] TJ
/GS1 gs
1 0 0 1 10 70 Tm
[(Banana)] TJ
/GS2 gs
1 0 0 1 10 60 Tm
[(Banana)] TJ
ET
~~~

As can be seen, the word "Banana" appears six times. The reason for this is that in `ShowTextProcessor#show_text` the method `.hello_world` is called as often as text is encountered on the page. Since in this case the wording 'Hello World!' appears two times, the method `.hello_world` is invoked two times. Therefore the opacities are overlayed and produce a different combined overlay opacity.

You can fix this by changing `ShowTextProcessor#show_text` to the following:

~~~ ruby
  def show_text(str)
    unless defined?(@shown)
      self.class.hello_world(@canvas)
      @shown = true
    end
  end
~~~

**Comment by konstantin-dzreev** [comment]
Got it, thanks for the explanation!
