### ISSUE TITLE
What's the future of hexapdf?

### ISSUE THREAD

**Issue by orklann** [gettalong/hexapdf#140]
As I know, this project is open source with paid commercial licenses, I am wondering how's the project going, How does the author get enough money to keep working on it?

Ok, What I want to know is: if the author sell enough commercial licenses so that he can keep on the development?

**Comment by gettalong** [comment]
HexaPDF was and is actively developed, with 18 releases in the past year. For now, my day job pays the bills and HexaPDF brings in additional funds which will hopefully sometime in the future be enough to make HexaPDF a full time gig. The number of customers is slowly but steadily rising so I think this is achievable.

Therefore I can make time for HexaPDF development and either implement features of my road map or features needed for potential new customers. This has worked great in the past two years. And since the source code is the same for the AGPL and the commercial license, the community also benefits. For example, support for digital signatures is the main goal of the next feature release and it was requested by both current and potential future customers.

**Comment by orklann** [comment]
A few years have passed, how is the bussiness going on? I am not going to know the exact number of your customers, but I am really interested in how is the bussiness going on with an open core and commercial licences for this kinds of open source project. Any info to tell?

**Comment by gettalong** [comment]
Hi @orklann! The business is going well. It would probably grow faster if I invested more time in marketing, customer acquisition and the likes but slow and steady wins the race. I would rather have existing customers satisfied than have many customers that need much support because that would take away time from HexaPDF development. Most of the current support requests deal with issues with troublesome PDFs which nearly always leads to enhancements in HexaPDF; so a win-win.

The major plus point for HexaPDF is that it is a very good product (in my opinion) in a niche with few competitors. This allows me more time to invest into the product itself instead of always looking out what the others are doing.

As the business is a B2B one, the price point is higher than in B2C products but the number of customers is lower. This takes off a lot of pressure, in my opinion. I *may* introduce a B2C product in the near future, though :wink:

**Comment by orklann** [comment]
Hi, @gettalong, thanks for your detailed information on this product. Nice to know that the bussiness is going better and better. It's an interest fact that you are  planning to also go for B2C while keeping this B2B bussiness, I think it's a awesome decision, such that a PDF SaaS product for end users would be a good choice for you especailly you are also creating a B2B PDF library. You are your own god for PDF SaaS without worring the tools you will use.

Anyway, I got a lot of inspiration from you as well. Thank you.

**Comment by gettalong** [comment]
@orklann Thanks :smile:

The product actually won't be a SaaS, that would be too much of a hassle :grin: It will be a plain old application that can be installed on one's computer and used without an internet connection. But you are right, it *will* be dealing with PDFs.

**Comment by orklann** [comment]
That's very interesting, if you are planning a desktop application with PDF, like PDF editor or so. And will you use HexaPDF library and also want it to be a desktop application? So that your application would be written in Ruby or you would like to rewrite all PDF functions with some language other than Ruby?

**Comment by gettalong** [comment]
Yes, this will be a desktop application that uses HexaPDF as basis for the PDF functionality, so it will be written in Ruby.

As for writing a PDF library in another language: I have a long-time goal of porting HexaPDF to Crystal.
