### ISSUE TITLE
Issue flattening annotations

### ISSUE THREAD

**Issue by earthlingworks** [gettalong/hexapdf#152]
Hello again! Most files are working ok for us but there are a few PDFs that get an error when flattening annotations. 

I'm going to share the code to duplicate the issue here and then I'll share one of the problem PDFs through email since I can't share publicly. 

```
require 'hexapdf'
​
file = File.open ARGV[0]
document = HexaPDF::Document.new(io: file)
document.pages.each(&:flatten_annotations)
```

**Comment by gettalong** [comment]
Thanks for providing the file!

The exception comes due to the fact that the file is invalid because one annotation's flags key is set to a float value of "4.0" instead of an integer of "4".

I will see how to best overcome this problem, most probably by introducing a new dictionary field converter module.

**Comment by gettalong** [comment]
@earthlingworks So the idea with the new field converter module works. Will put this into a bug fix release.

**Comment by gettalong** [comment]
@earthlingworks HexaPDF 0.16.0 released with the needed change!

**Comment by earthlingworks** [comment]
Already replied through email but yes, this release fixed the issue for us. Thank you!
