### ISSUE TITLE
link to embedded file?

### ISSUE THREAD

**Issue by joshco** [gettalong/hexapdf#153]
How do i make a link to an embedded file?

I'm using composer for most of the text in the pdf, and composer.document to do the files.
I've already got the embedded files added in the files collection and can view them from the reader's embedded files UI pane.

However, I can't figure out to make the link to those files.
Ideas?

**Comment by gettalong** [comment]
So you want to make a link similar to a hyperlink to a web page but to one of the embedded files? This is possible with File Attachment Annotations, however, there is no convenience support currently built into HexaPDF to use them.

I will see what it would take to implement them.

**Comment by joshco** [comment]
Yeah, I'm more focused on the functionality rather than styling.  I looked at the issue on actions, and the PDF spec talks about the go_to_e with the N param.  However, I couldn't figure out how I emit that inline with the text I'm outputting.
Imagine a table of files, I want to put a clickable link to the embedded file.  Not all users are familiar with the embedded files tab in reader...

| FIlename         | description
|-----------------|-----------------------------------------------------
| old_newspaper| A newspaper from back in ye olde days
| term_paper     | an old term paper

**Comment by gettalong** [comment]
Yeah, there is the GoToEmbedded action but I think it is not the correct one. From what I gather using a file attachment annotation would be the way to go.

**Comment by gettalong** [comment]
@joshco Try the following for the time being:

~~~ ruby
require 'hexapdf'

HexaPDF::Composer.create("out.pdf") do |c|
  f = c.document.files.add("/tmp/machupicchu.jpg")
  s = c.base_style.dup
  s.overlays.add do |canvas, box|
    page = canvas.context
    matrix = canvas.graphics_state.ctm
    quad_points = [*matrix.evaluate(0, 0), *matrix.evaluate(box.width, 0),
                   *matrix.evaluate(box.width, box.height), *matrix.evaluate(0, box.height)]
    x_minmax = quad_points.values_at(0, 2, 4, 6).minmax
    y_minmax = quad_points.values_at(1, 3, 5, 7).minmax
    annot = {
      Subtype: :FileAttachment,
      Rect: [x_minmax[0], y_minmax[0], x_minmax[1], y_minmax[1]],
      QuadPoints: quad_points,
      FS: f,
      Name: :Something,
    }
    (page[:Annots] ||= []) << page.document.add(annot)
  end
  c.formatted_text([{text: "Hallo", style: s}])
end
~~~

This custom overlay adds a file attachment annotation and in my limited testing it appears to do what you want. If that is the case, I will add a proper implementation for this.

**Comment by joshco** [comment]
I tried this.  It puts the icon stretched over the text.
![image](https://user-images.githubusercontent.com/290314/136052914-269eeb96-1d3c-4106-b596-d8c19dc1d5ba.png)
I've also been exploring Collection in the catalog. Which is actually a really neat UI.

![image](https://user-images.githubusercontent.com/290314/136055241-989ce493-857f-4245-a19c-baa8f13f81d4.png)

Alas, I'm not hearing that the project requirements may prohibit embedded files altogether... I need to merge inline the content of the files' pages.  So now I'm looking to intersperse the merged pages with section header pages.  
Composer is pretty neat, but it would be super helpful if it could output a semantic tag like a header eg (like H1 H2 H3), and simple links   If that was simple, then I could easily manually generate a TOC page either in hand made links, or figure out how to emit the Outlines catalog entry and a TOC.  
For comparison, I'm also using Pandoc in the project to generate more complex reporting pages from markdown source.
But that doesnt handle the inclusion of grabbing pages from other existing PDFs (except when my code grabs the page and converts it to a PNG, but that makes the files sizes too large).

**Comment by gettalong** [comment]
Hmm... while testing I saw the stretched image, too. But once I added `/Name /Something` (which defines the icon to be used), the images were not used in the viewers I tested (on Linux). You can try setting an empty appearance stream for the annotation which should prevent viewers from using a default appearance.

You can easily import pages from other PDF files and insert them anywhere like an image. If the other PDF has just one page, you can just use `canvas.image(pdf_file, ...)`. Otherwise, use `form = target.import(source.pages[PAGE_NR]).to_form_xobject` and treat `form` like you would an image. Naturally, you could also just import a page as a real page if necessary, see https://hexapdf.gettalong.org/examples/merging.html.

Composer is currently pretty bare-bones. What you can do is something like this to emulate paragraphs of different styles and links:

~~~
require 'hexapdf'
HexaPDF::Composer.create('output.pdf') do |composer|
  h1 = composer.base_style.dup.update(font_size: 24, align: :center, padding: [12, 0])
  link = composer.base_style.dup.update(fill_color: [0, 0, 255], underline: true)
  composer.text("Some header", style: h1)
  composer.text("Some paragraph like text")
  composer.formatted_text(["Some text here", {text: "linked", style: link, overlays: [[:link, uri: 'https://hexapdf.gettalong.org']]}])
end
~~~

**Comment by gettalong** [comment]
@joshco Is there still something to do for this issue?

**Comment by joshco** [comment]
not right now.  I'm exploring another approach (than embedded files)
