### ISSUE TITLE
`:Helvetica can't be coerced into Integer` while saving field value

### ISSUE THREAD

**Issue by ksocha** [gettalong/hexapdf#155]
Hi @gettalong 

I've encountered the above error while setting a string value as field value.
`#<TypeError: :Helvetica can't be coerced into Integer>`

The doc I've used is the same I sent you in #148 
Field name is: `Account no`

Stacktrace:
```
"/hexapdf-0.16.0/lib/hexapdf/layout/style.rb:1005:in `*'",
"/hexapdf-0.16.0/lib/hexapdf/layout/style.rb:1005:in `calculated_font_size'",
"/hexapdf-0.16.0/lib/hexapdf/layout/style.rb:1034:in `scaled_font_size'",
"/hexapdf-0.16.0/lib/hexapdf/type/acro_form/appearance_generator.rb:392:in `draw_single_line_text'",
"/hexapdf-0.16.0/lib/hexapdf/type/acro_form/appearance_generator.rb:261:in `block (2 levels) in create_text_appearances'",
"/hexapdf-0.16.0/lib/hexapdf/content/canvas.rb:250:in `save_graphics_state'",
"/hexapdf-0.16.0/lib/hexapdf/type/acro_form/appearance_generator.rb:253:in `block in create_text_appearances'",
"/hexapdf-0.16.0/lib/hexapdf/content/canvas.rb:1835:in `marked_content_sequence'",
"/hexapdf-0.16.0/lib/hexapdf/type/acro_form/appearance_generator.rb:251:in `create_text_appearances'",
"/hexapdf-0.16.0/lib/hexapdf/type/acro_form/text_field.rb:220:in `block in create_appearances'",
"/hexapdf-0.16.0/lib/hexapdf/type/acro_form/field.rb:254:in `each_widget'",
"/hexapdf-0.16.0/lib/hexapdf/type/acro_form/text_field.rb:217:in `create_appearances'",
"/hexapdf-0.16.0/lib/hexapdf/type/acro_form/text_field.rb:226:in `update_widgets'",
"/hexapdf-0.16.0/lib/hexapdf/type/acro_form/text_field.rb:170:in `field_value='",
```

I'm not certain if this is something that should be handled by the lib, or the pdf itself is faulty in some way.

**Comment by gettalong** [comment]
So it seems that some of the /DA values of that PDF are invalid because they contain `"//Helvetica 12 Tf 0 g"` - note the double slash.

According to the PDF spec: *"The token SOLIDUS (a slash followed by no regular characters) introduces a unique valid name defined by the empty sequence of characters."*.

This means that `//Helvetica` are actually two object, an empty name object `:""` and `:Helvetica` which messes up the number of operands for the `Tf` operator which expects two operands, font name and size. In this case `:Helvetica` gets assigned to the size variable leading to the error.

So we will probably need to work around this.

**Comment by gettalong** [comment]
@ksocha This is fixed in the next release.
