### ISSUE TITLE
Support for creation of outlines (bookmarks)

### ISSUE THREAD

**Issue by mikevoets** [gettalong/hexapdf#16]
Is there any support for outlines (bookmarks) in the current version? In my application I am using Prawn and would love to try to switch to hexapdf, which seems to have much better support for merging documents. However, outline creation seems not to be supported yet.

I'd love to extend hexapdf with support for outline creation, but before I start I would like to know if anyone has arguments against having that functionality in hexapdf.

**Comment by gettalong** [comment]
No, there is currently no support for outlines. This feature is on my TODO list but it will probably be some time before I will implement it.

If you want to implement this feature, the document outline features is documented in PDF 1.7 section 12.3.3. However, since activating an outline item implies executing an action (see PDF 1.7 section 12.6) or showing a destination (see PDF 1.7 section 12.3.2), the implementation scope is larger than just "document outline" since neither actions nor destinations are implemented, yet.

You might want to look at how embedded files are handled and implemented, see https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/document/files.rb and the file specific type classes in https://github.com/gettalong/hexapdf/tree/master/lib/hexapdf/type.

Please also note that I need as signed contributor license agreements for all contributions to HexaPDF (see https://hexapdf.gettalong.org/contributing.html).

**Comment by gettalong** [comment]
@mikevoets I will close this issue - if you follow the release news there will be a note regarding document outlines once they are supported in an easy to use manner.
