### ISSUE TITLE
Argument error on PDFs

### ISSUE THREAD

**Issue by earthlingworks** [gettalong/hexapdf#167]
Hey Thomas! I have two different PDFs getting the same error:

> ArgumentError ("+HH:MM", "-HH:MM", "UTC" or "A".."I","K".."Z" expected for utc_offset)

Code to reproduce:

```
require 'hexapdf'
​
document = HexaPDF::Document.open(ARGV[0])
document.write('/tmp/test.pdf', validate: false, optimize: true)
```

I'll send the PDFs through email. Thanks!

**Comment by gettalong** [comment]
Thanks for the files!

I have looked at the first one and it seems that it used invalid timestamps, ie. `D:01211016165909+00'64'`. I will probably just ignore such timestamps and return null values for them.

**Comment by gettalong** [comment]
@earthlingworks Just a quick update: The regular expression for matching valid dates was a bit too relaxed for the invalid timestamps in this file. I have modified it to be a bit more strict (while still allowing for the various [invalid] variations found in the wild).

It seems the timestamps in those files weren't properly converted to the needed format because the example I have given above would refer to the year 121...

I will push a fix release later today.

**Comment by gettalong** [comment]
@earthlingworks Just released the new version with the fix.

**Comment by earthlingworks** [comment]
Great, thank you!

Ruben
------------------------
Founder, http://www.bidsketch.com
Twitter: http://twitter.com/bidsketch
