### ISSUE TITLE
PDF is showing 0 pages

### ISSUE THREAD

**Issue by earthlingworks** [gettalong/hexapdf#169]
Hey Thomas, for some reason we have a PDF that seems ok in Acrobat but it's showing up as having 0 pages in HexaPDF. 

```
>> doc = HexaPDF::Document.open '/path-to-folder/pdf-pages.pdf'
>> doc.pages.count
=> 0
```

I'll send the PDF through email; thanks!

**Comment by gettalong** [comment]
If you get such a file you can run `hexapdf info --check file.pdf` to see what HexaPDF thinks about the file in terms of structural and validation problems.

In this case HexaPDF doesn't find the end-of-file marker although it is surely there (just looked at the file in an editor). The reason for this is that the `startxref` keyword and the position are on the same line instead of two different lines as mandated by the spec. I will add a workaround for such invalid files.

**Comment by gettalong** [comment]
@earthlingworks I have added the work-around for the invalid "startxref VALUE" situation and the file can now be handled by HexaPDF without problems. HexaPDF 0.19.3 with the fix was just released.

**Comment by earthlingworks** [comment]
@gettalong Great; we'll get the fix in right away, thank you! And thanks for the tip about checking the file.
