### ISSUE TITLE
Need to put dynamic text by replacing any text -

### ISSUE THREAD

**Issue by vivek1234567890** [gettalong/hexapdf#170]
I have an application in Ruby on Rails. I have some predefined Pdf templates which include some dynamic variable like {{firstname}}, {{lastname}}, {{email}} etc. I want to replace these text with dynamic data in pdf without affecting the pdf formatting like font size and color. 
Any help(code snippet) would be appreciated.

**Comment by gettalong** [comment]
HexaPDF doesn't have any text reflow capabilities. Finding that text and replacing it with something else will work. However, **all other text** will stay the same, e.g. at the same position. This means that if the surname is longer than your placeholder text, it will overlap with the following text.

If this is of no concern to you, have a look at https://hexapdf.gettalong.org/examples/show_char_bboxes.html to see how to process an existing page. Once you have found the position of your placeholder text, use an overlay canvas to draw the needed text at the found position.

**Comment by gettalong** [comment]
@vivek1234567890 Another idea: Don't use the dynamic variables but use form fields. Then you don't need to do the hard text processing part but can just iterate over the form fields, fill them out and then flatten the form. Note, however, that for this to work you would still need to ensure that the form fields are big enough as there would still not be any text reflow.

I will close this issue now since I don't think there is anything else to do here. Feel free though to comment or open a new issue if you think otherwise!
