### ISSUE TITLE
[Documentation] Could the main README state whether hexapdf works on windows by default as well, and whether one can generate .pdf files on windows too?

### ISSUE THREAD

**Issue by rubyFeedback** [gettalong/hexapdf#173]
(My apologies for the rest of this issue request being written in german, save for the last TL;DR part, but it feels a bit more appropriate to use slight ~viennese slang. :D)

Sers Thomas,

Ich habe ein paar ruby gems die aktuell prawn verwenden. Im README führst du an das ein Ziel von hexapdf
sein wird, das hexapdf ähnlich wie prawn verwendet werden kann (also "content generation", sprich, ein .pdf
Dokument erstellen).

Für das Jahr 2022 plane ich all meinen prawn-spezifischen code durchzusichten und zu adaptieren; das inkludiert
auch hexapdf (vor allem da du um einiges aktiver bist als die prawn maintainers, zumindest die primären 
Entwickler dort). Also auf meiner "todo" Liste steht auch die Möglichkeit hexapdf zu verwenden. Aktuell 
verwende ich hexapdf nur ganz wenig; denke es gab einen Aspekt der mit qpdf zu tun hatte (wenn dir 
das was sagt; ich hatte da Anwendungsgebiete für einen ruby-gtk3 editor. Auch auf meiner TODO Liste
steht einen pdf-viewer zu machen in ruby-gtk3, aber bis das mal so sein wird vergeht wohl noch einige
Zeit ... wäre aber nett wenn man das einfach machen könnte.)

Dies als ersten Schritt zumindest mit Wahlmöglichkeiten hin sowohl prawn als auch hexapdf zu verwenden,
aber wenn hexapdf die selbe Möglichkeiten bietet wie prawn (zumindest für EINFACHE .pdf; ich brauch 
da nix super-fancy, wirklich nur font, size, bissi Farben ... href hyperlinks ... das war es eigentlich schon.
Vielleicht auch image-logo aber wirklich eigentlich nur grundlegende Sachen).

Einer meiner gems ist für Studenten gedacht, quasi ein "exam trainer", zum Teil nicht ganz unähnlich
dem python "anki" wenn dir das was sagt - aber nicht so professionell. Eben mehr ein Hobby Projekt.

Darin verwende ich auch sinatra/www-Zeug, auch ruby-gtk3 und ruby-libui - also GUIs. Eine weitere
Komponente ist die Möglichkeit .pdf Dateien zu erstellen. Da die meisten Studenten jedoch windows
verwenden möchte ich das ganze möglichst einfach gestalten, so das die das auch auf Windows 
verwenden können. (Ich selbst benutze 95% meiner Zeit Linux, hab aber auch einen Windows Rechner
zum Testen.)

Von daher wäre es nett wenn das main README einfach nur kurz erwähnen könnte ob hexapdf auch
auf Windows funktioniert. Also ob man ein einfaches "hello world!" Text .pdf erzeugen kann auf
windows, also nach dem ruby-one-click-installer, dann "gem install hexapdf". Ich hab das noch nicht
getestet da ich eigentlich fast nur prawn-spezifischen code habe; das ist jedoch ein Vorsatz von
mir 2022 hexapdf genauer zu begutachten. Ich mach das dann immer über einige Tage, wo ich
neue Information in lokale Dateien reinschreib, so das ich mich dann später ah wieder auskenne.

Mehr PDF-Zeug auf ruby ist sowieso super leiwand - ok das wars!

TL;DR: "**Please consider adding to the main README of hexapdf whether hexapdf works on
windows as-is, in order to inform potential users whether they can use hexapdf on windows or
not**."

**Comment by gettalong** [comment]
> Ich habe ein paar ruby gems die aktuell prawn verwenden. Im README führst du an das ein Ziel von hexapdf
sein wird, das hexapdf ähnlich wie prawn verwendet werden kann (also "content generation", sprich, ein .pdf
Dokument erstellen).

Genau, das kann HexaPDF bereits.

Die low-level Variante ist einfach die Benutzung [HexaPDF::Content::Canvas](https://hexapdf.gettalong.org/documentation/reference/api/HexaPDF/Content/Canvas.html):

~~~ ruby
require 'hexapdf'

doc = HexaPDF::Document.new
canvas = doc.pages.add.canvas
canvas.font('Helvetica', size: 10).text("Hello World!", at: [100, 400])
doc.write('hello-world.pdf')
~~~

Die high-level Variante ist die Benutzung von [HexaPDF::Composer](https://hexapdf.gettalong.org/documentation/reference/api/HexaPDF/Composer.html). Aktuell kann man da Texte und Bilder ausgeben lassen. Geplant sind Tabellen, Spalten, etc. Prawn ist in dieser Hinsicht aktuell aber noch besser aufgestellt und einfacher zu benutzen.

Siehe auch die Beispiele:

* https://hexapdf.gettalong.org/examples/hello_world.html
* https://hexapdf.gettalong.org/examples/text_in_polygon.html
* https://hexapdf.gettalong.org/examples/frame_automatic_box_placement.html
* https://hexapdf.gettalong.org/examples/composer.html

> Für das Jahr 2022 plane ich all meinen prawn-spezifischen code durchzusichten und zu adaptieren; das inkludiert
auch hexapdf (vor allem da du um einiges aktiver bist als die prawn maintainers, zumindest die primären
Entwickler dort). Also auf meiner "todo" Liste steht auch die Möglichkeit hexapdf zu verwenden. Aktuell
verwende ich hexapdf nur ganz wenig; denke es gab einen Aspekt der mit qpdf zu tun hatte (wenn dir
das was sagt; ich hatte da Anwendungsgebiete für einen ruby-gtk3 editor. Auch auf meiner TODO Liste
steht einen pdf-viewer zu machen in ruby-gtk3, aber bis das mal so sein wird vergeht wohl noch einige
Zeit ... wäre aber nett wenn man das einfach machen könnte.)

Ja, qpdf sagt mir natürlich was. Ist ein super Projekt und ich verwende es hauptsächlich für `qpdf --check`, also zum überprüfen, wie qpdf auf PDF-Dateien reagiert. Und es ist Teil es [Optimization Benchmarks](https://hexapdf.gettalong.org/documentation/benchmarks/optimization.html) - qpdf ist ja in C++ geschrieben und damit kann man gut die hexapdf CLI und die qpdf CLI für ähnliche Operationen vergleichen.

PDF-Viewer ist ambitioniert, aber wenn du GTK3 verwendest, sollte da auch Cairo mit dabei sein. D.h. wenn du die PDF-Zeichenbefehle auf Cairo-Befehle umlegen kannst, sollte es nicht einmal so schlecht funktionieren. Da ist der einzige Teil der PDF-Spezifikation, den ich explizit ausgeschlossen habe zu implementieren, also alles, was die Anzeige von PDF-Dateien betrifft.

> Dies als ersten Schritt zumindest mit Wahlmöglichkeiten hin sowohl prawn als auch hexapdf zu verwenden,
aber wenn hexapdf die selbe Möglichkeiten bietet wie prawn (zumindest für EINFACHE .pdf; ich brauch
da nix super-fancy, wirklich nur font, size, bissi Farben ... href hyperlinks ... das war es eigentlich schon.
Vielleicht auch image-logo aber wirklich eigentlich nur grundlegende Sachen).

Die von dir genannten Sachen kann HexaPDF alle, siehe z.B. https://hexapdf.gettalong.org/examples/text_layouter_styling.html.

> Von daher wäre es nett wenn das main README einfach nur kurz erwähnen könnte ob hexapdf auch
auf Windows funktioniert. Also ob man ein einfaches "hello world!" Text .pdf erzeugen kann auf
windows, also nach dem ruby-one-click-installer, dann "gem install hexapdf". Ich hab das noch nicht
getestet da ich eigentlich fast nur prawn-spezifischen code habe; das ist jedoch ein Vorsatz von
mir 2022 hexapdf genauer zu begutachten. Ich mach das dann immer über einige Tage, wo ich
neue Information in lokale Dateien reinschreib, so das ich mich dann später ah wieder auskenne.

Ja, das geht. Ich teste zwar nicht auf Windows, aber nachdem HexaPDF quasi ohne Dritt-Abhängigkeiten auskommt (nur von mir selbst geschriebene, i.e. cmdparse und geom2d werden verwendet), sollte HexaPDF unter Windows eigentlich komplett funktionieren.

[Hier](https://www.reddit.com/r/pdf/comments/l1tbcm/batch_convert_pdf_files/gk9qd6n/?utm_source=reddit&utm_medium=web2x&context=0) zum Beispiel habe ich jemanden ein HexaPDF-Skript geschrieben für die automatisierte Verarbeitung von PDF-Dateien. Da findest du auch die Anleitung zur Installation unter Windows - das hat alles ganz wunderbar geklappt.

> TL;DR: "Please consider adding to the main README of hexapdf whether hexapdf works on
windows as-is, in order to inform potential users whether they can use hexapdf on windows or
not."

Will do :)
