### ISSUE TITLE
How to edit/remove the PDF Producer?

### ISSUE THREAD

**Issue by ruinunes** [gettalong/hexapdf#175]
My pentester is arguing that revealing the PDF Producer gives too much information.
<img width="416" alt="image" src="https://user-images.githubusercontent.com/2411102/152968529-e6d717a1-6561-4948-83cc-468b7d03b305.png">
Is there a way to change the metadata/properties?

**Comment by ruinunes** [comment]
Found a solution by extending `HexaPDF::Writer`.
`CustomWriter < HexaPDF::Writer`
and overwriting the `write` method.

But I wonder if there is any other way.

**Comment by gettalong** [comment]
It depends on the license, i.e. whether you are using the AGPL version or the commercial version. With the AGPL version you are not allowed to change the producer, see https://github.com/gettalong/hexapdf/blob/master/LICENSE#L24-L26. Therefore it is intentionally not that easy to change it.

The commercial license doesn't have this provision, so you are allowed to remove the mentioning of HexaPDF. In this case I would prepend a module:

~~~ ruby
module RemoveProducer
  def write
    write_file_header

    pos = xref_section = nil
    @document.revisions.each do |rev|
      pos, xref_section = write_revision(rev, pos)
    end

    xref_section
  end
end
HexaPDF::Writer.prepend RemoveProducer
~~~

The disadvantage is that you have to take care of this when updating to a new version. However, that code doesn't change much. There was a change recently due to the introduction of digital signatures but it will probably stay this way.

**Comment by ruinunes** [comment]
@gettalong yes, this what we're looking for. Thanks for the explanation and your time.
Love working with this gem btw 👍

**Comment by gettalong** [comment]
> Love working with this gem btw +1

@ruinunes Thanks! :smile: If you come across any pain points (except the one discussed here :grin:), please let me know!

**Comment by gettalong** [comment]
@ruinunes Just a heads up: There will be changes to `Writer#write` and `Writer#write_incremental` with the upcoming release, so you will need to adjust your code once you update to that release.

**Comment by ruinunes** [comment]
Acknowledged, thanks. 
I didn't mentioned before - but yes - our customer is using the commercial license.
