### ISSUE TITLE
Unexplained conversion from space character to non-breaking space character (nbsp)

### ISSUE THREAD

**Issue by eric-hemasystems** [gettalong/hexapdf#178]
My code writes text to on top of a PDF. Some snippets that come from inside a class are:

```ruby
def text value, at:, font: 'Source Sans Pro', size: 10
  return if value.nil?

  canvas.font font, size: size
  canvas.text value.to_s, at: at.collect(&:to_i)
end

def canvas
  @canvas ||= page.canvas type: :overlay
end

def page
  document.pages.first.tap { _1.rotate 0, flatten: true }
end

def document
  @document ||= HexaPDF::Document.new(io: background_io).tap do |doc|
    doc.fonts.add 'Source Sans Pro' # Embed font into document
  end
end

def background_io
  StringIO.new @configuration.background.download
end
```

In my test suite I'm basically running:

```ruby
text 'Order number', at: [10, 10]
```

to write the literal string "Order number" into the PDF.

To verify the content is in the PDF I use the following utility class in my test suite:

```ruby
# Based on https://github.com/gettalong/hexapdf/issues/18
class PdfTextExtractor < HexaPDF::Content::Processor
  attr_reader :texts

  class << self
    def extract document
      extractor = new
      document.pages.each { _1.process_contents extractor }
      extractor.texts.join ' '
    end

    def extract_from_io io
      document = HexaPDF::Document.new io: io
      extract document
    end
  end

  def initialize
    super
    @texts = []
  end

  def show_text str
    @texts << decode_text(str)
  end
  alias :show_text_with_positioning :show_text
end
```

The idea is to extract all text from the resulting PDF and see if my written content is at least on the page. This test used to pass but I recently changed the font from the PDF built-in Helvetica to [Source Sans Pro](https://fonts.google.com/specimen/Source+Sans+Pro). After making that change I get back "Order Number" but instead of a space character (ASCII 32) I get back a non-breaking space character (ASCII 160).

Even more weird is that I am 75% certain I ran this test after making the font change and it passed. But now with no changes it is failing. Furthermore I am 100% certain the test with the new font passed on CI. Is there anything within the HexaPDF library that could explain the character change? I could of course update my test to use a regex so any type of space would work. But figured I would ask to see if there is something that is causing this transformation.

**Comment by gettalong** [comment]
So for this I have to dig a little bit into how TrueType fonts and using embedded TrueType fonts work.

TrueType fonts store the information about a glyph (a visual representation of a character) in various parts, so called tables, of the file. For example, there is one table which contains the widths of the glyphs and another that contains the font programs themselves. To access the information for a certain glyph, the *glyph ID* is needed which can be thought of an index into the various "arrays".

Another TrueType table allows the conversion from character code (e.g. Unicode codepoint) to glyph ID. This functionality is used by HexaPDF to map a string of characters to an array of glyph objects via the glyph ID.

When the TrueType font gets embedded into the PDF, there is *another* mapping from PDF character ID as used in the content streams directly to TrueType glyph ID. This allows us to drop some TrueType tables while embedding and make the file size smaller.

Since the PDF content stream uses character IDs instead of ASCII or Unicode or any other encoding, we not only need to get the visual representation of that character ID (i.e. the glyph) but also the Unicode codepoint for text extraction. To do this a mapping from character ID to Unicode is stored in the PDF.

This mapping is created by HexaPDF by looking at the used glyphs and then reverse-mapping via the TrueType tables to their Unicode codepoints. See https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/font/true_type/table/cmap_subtable.rb#L109-L114

However, as pointed out in the docs this mapping may not be unique in that direction since a single glyph could be used for multiple codepoints!

And I'm fairly sure that this is happening in your case if you are using both the space and the non-breaking space character.

As for why it worked and now it doesn't: Are you sure you are still using the exact same font file? If not, that could be the reason.

I have an item on my TODO list to fix that but since it is normally not a problem it has low priority.

**Comment by eric-hemasystems** [comment]
Thanks for the explanation.

The font file where the test pass (on CI) is the same as where it doesn't pass (on my local machine) as they are all out of the same repo. But they are different systems (Mac vs Linux) so maybe that has something to do with it.

As far as I know there is not a nbsp already on the PDF. I made the PDF loaded myself for the test suite to be just a blank PDF via the command `convert xc:none -page Letter background.pdf`. In the application users won't be uploading blank documents but for the purposes of the test I just wanted it to load an existing PDF, write some text, output to a new PDF and verify that text was written to the resulting PDF.

Regardless I suspect you are correct that somehow the space glyph is being mapped to multiple code points and for some reason it the nbsp is the chosen codepoint instead of the regular space. I updated my test suite to not care what type of space character came back which is good enough.

Going to close this issue as there isn't really anything to do within HexaPDF and the mystery is mostly solved.
