### ISSUE TITLE
Does Type1 use font subsetting just like Hexapdf did to True Type font

### ISSUE THREAD

**Issue by orklann** [gettalong/hexapdf#180]
Hello, It seems Type1 fonts do not subset just like you did to True Type font, is it right? I am not sure, just reading the source code, and I can not find any subsetter for Type1 fonts.

**Comment by gettalong** [comment]
You are completely right, Type1 fonts are not subset by HexaPDF. The simple reason for this is that the only supported Type1 fonts are the built-in standard PDF fonts which do not need to be embedded or subset to be available because these font files need to be installed by default by each PDF reader.

**Comment by orklann** [comment]
Yeah, If only 14 standard Type1 fonts can be handled, then no need to subset them, because they are assumed to be embedded in the PDF processor.

But is it always true that, there is no embedded Type1 fonts in PDF, I mean can we embed Type1 fonts (Not the 14 core fonts) into a PDF file?

**Comment by gettalong** [comment]
Yes, generally speaking, arbitrary Type1 fonts can be embedded, either in full or subset. However, HexaPDF doesn't support such Type1 fonts, only TrueType fonts.

**Comment by orklann** [comment]
Thank you for great answer. :D
