### ISSUE TITLE
[Smallish idea] Example for creating a new .pdf file, similar to "hexapdf modify", but specifying which pages to KEEP rather than remove

### ISSUE THREAD

**Issue by rubyFeedback** [gettalong/hexapdf#181]
Sers gettalong,

You offer an example and feature to create a new .pdf file such as this:

    hexapdf modify input.pdf -i 1-5,7-10,12-e output.pdf

Documentation states:

    Page removal: Remove the pages 6 and 11 from the input.pdf.

I have a similar use case, but an elderly relative needs to specify
which pages to KEEP, then create a new .pdf file from that.

I assume this is possible; I think I can even combine this as-is,
e. g. first extract the pages from the .pdf file, then merge it.
But I was also thinking that perhaps an example could be
added that shows the opposite, e. g. rather than DELETE these
pages, we end up KEEPING these files, e. g. "keep page 
1,5,6,12 and create a new .pdf file".

If that is already possible then perhaps this could be added below
the above example.

To find it faster if need be, I got it from this URL:

https://hexapdf.gettalong.org/documentation/reference/hexapdf.1.html

**Comment by rubyFeedback** [comment]
Aha - just found this here:

https://www.viget.com/articles/splitting-pdfs-with-hexapdf/

That was a very nice read with explanation too. \o/

So I guess this request here is mostly just a documentation-improvement if you ever find some time. Probably no
change to the code is necessary.

**Comment by gettalong** [comment]
Thanks for making me aware of this!

So, I think this stems from me knowing that `hexapdf modify` can naturally also be used for page selection. E.g. the documentation for the example you mentioned could also just be: "Page selection: Select only the pages 1 to 5, 7 to 10, and 12 to the end."

Since I thought this use case was obvious I didn't provide an explicit example. The documentation for the `modify` command says: *"It can be used to select pages that should appear in the output file and/or rotate them. "*.

I will add another example that explicitly does page selection.
