### ISSUE TITLE
[Question / Feature request, but more a question] Autogenerating .pdf file for a "gamebook" style .pdf with some custom formatting: how feasible would it be to use hexapdf for this?

### ISSUE THREAD

**Issue by rubyFeedback** [gettalong/hexapdf#198]
Hey there gettalong,

This is more of a support-question query, but before dismissing it right
away, perhaps you could briefly read it nonetheless - thank you for your
time "upfront".

Before I explain this suggestion or proposal or request in more detail,
allow me to explain the background and rationale here.

In the 1980s there used to be "gamebooks" or "fighting fantasy books".
This refers to hardcopy books that you could purchase for, say, 10 or
20 euro or so - like 200 Schilling. :P (In Austria these were
popular by the "Thienemann Verlag", but they were published in the
UK actually, for the most part, excluding a few german-centric
gamebooks.)

For instance, these would look like this from the Thienemann Verlag:

https://i.imgur.com/lX8rYI2.jpg

I still have the whole original collection but unfortunately the 
pages are yellow-ish. I should have perhaps sealed them off from
the air and what not ... anyway.

I do not know whether you have heard of these gamebooks, or perhaps
if you had, may not remember them.

You could read a page in such a gamebook, and then you would jump
to another subpage such as "go to entry 33", depending on choices you
would make. So you had multiple different paths to complete the 
gamebook (or the actor may perish too). You may typically have fights
in the book as well, and other challenges, and roll a die to determine
the outcomes.

In the english original, the name for "Spielbuch" was "Fighting
Fantasy", which, IMO, makes more sense. But anyway.

So, basically, to re-wrap, it was like a fantasy novel (usually) where
you could decide on which path to pursue next.

Some time ago I decided to start writing code to support this too,
for the computer.

The project I bundle all my legacy stuff from my old pen and paper
group in the 1990s is here at:

https://rubygems.org/gems/rpg_paradise
https://www.rubydoc.info/gems/rpg_paradise

The ruby-gtk3 wrapper for the gamebook currently looks like this:

https://i.imgur.com/GgfEv4D.png

Yes, not quite as epic as the old gamebooks, but I am more interested
in polishing the functionality as-is. At some later time in point I
may improve upon it.

For instance, I had a look around at other projects and their GUI is
really neat - this is one example:

https://i.imgur.com/5MpXtCb.jpg

It has a game-y interface. And clickable elements.

Also have a look at the background of the image I just linked
^^^ above; I'll get to this point in a moment. I like that
parchment style, simulating a book or a parchment.

Anyway.

You may now wonder "but what does this have to do with hexapdf
and .pdf files?"

Well - there are some gamebooks available that are stored in
a .pdf file, if you search for them on the www.

For instance, a  german-centric variant ("Das Schwarze Auge",
if you ever heard about this) can be seen here:

https://www.dsa-schatztruhe.de/abenteuer/solo/reise.pdf

If you can and have time, please have a look at that .pdf file
just very briefly, in particular some place in the middle of
that .pdf file or so. This part is more relevant to hexapdf,
so it explains why I write this here.

If you look at that linked in .pdf page, then the subpage gets
a large number (large header), say "22", and below that header
you can then find the paragraph for entry 22. It is neatly
arranged in what I call a box or a rectangle. I remember
on prawn you can lay out boxes, and write into them, I think?

Anyway. Then, say after the paragraph, the exits to other
subpages are listed "go left, 123, go right, 255" and so on
and so forth.

The individual page of this .pdf file is typically split in
two parts, so these paragraphs are on both sides of an
individual page - on the left hand side, and on the right hand 
side.

I would like to be able to re-create such a .pdf file, hence
why I want to use hexapdf for this. I have all the required
data for gamebooks in a .yml file (or, I can populate it; I
am mostly looking for free and permissive ones to re-use)
and I can control everything data-related via ruby as well
as automatic styling and generation via hexapdf or prawn or
whatever, so this is not the problem that I have really.

But, right now I do not know whether I could use hexapdf for
this job actually.

I would like to be able to programmatically generate .pdf files
that way, so that people, who prefer, can read a .pdf rather
than use a GUI (such as a ruby-GUI or a web-interface; the
ruby-gtk3 is currently my main prototype. I intend to
eventually add a complete web-interface as well).

My basic goal is to be able to generate such a .pdf file
as linked above.

So, my primary question here is the following:

- Do you think it is possible to use hexapdf to generate such
a .pdf file?

It does not have to be identical. But it should allow for
the primary functionality to exist.

I thought about what this would need so I think the following
list needs to be satisfied:

(As a reminder, here is the .pdf file again:)

https://www.dsa-schatztruhe.de/abenteuer/solo/reise.pdf

(1) Be able to number the individual page, ideally on the
bottom right area. So if 50 pages are generated, each
page should have a number displayed on the bottom
right area. Here I do not necessarily need to use hexapdf
but it would be nice if hexapdf supports this as-is.

(2) Be able to use intra-links in the .pdf file. I can
programmatically tell hexapdf where these individual 
pages link into, just like a HTML intralink, but I would
need functionality in hexapdf to support "in-pdf-page-jumping"
if that is possible. I believe it should be possible; in
libreoffice I can do so via the intralinks and the resulting
.pdf file supports this. So I think this should be in theory
possible. I am not sure if hexapdf supports this, but if it
already does, please ignore this entry here.

(3) Be able to group the paragraphs into a box, with a
header. I can probably use a specialized class for this,
but I need to be able to put it on that individual page
in a way so that the text does not "outflow" from that
box. Perhaps even calculate how many boxes are needed,
but this is not so important - I am fine with a hardcoded
listing too, say, 3 entries per side (left and right)
so 6 entries per individual page in that .pdf file. That
would be sufficient. Other solutions are fine too, a
basic solution too. I'd love if I can support some
colours too, but this is optional (ruby could generate
the colouring or different fonts and what not).

(4) Optionally I would like to be able to embed small
images, within a given subpage, such as showing how the
sword looks like that the main hero (the actor) just
found. For instance, the original fighting fantasy books
had a die/dice image on the bottom area. This allowed
you to roll-a-die and get a result, and continue to 
play the book even if you did not have a physical die.
I liked this functionality. It's not shown on the above
.pdf file but the following image shows this:

https://i.imgur.com/6d0ComQ.jpg

(By the way, this is not my image, but my books also
have this yellow colouring now :( - they used to
be white in the 1980s ...)

You can see the die on the bottom area. Actually two
dice. Other books had one die on the bottom right or
bottom left.

So being able to generate such images, but also to
embed images in the middle of such an individual
paragraph, may be fine.

Anyway. This is more a support question I guess, 
but I promise I will diligently read all your
answers - I have bookmarked this locally into my
todo-list for gamebooks in the rpg_paradise project
now, so I won't forget it. I don't need you to write
the code for me, naturally, I will do so on my own.
But any help is appreciated.

In particular, the two main questions (aside from
"is this possible in hexapdf") is in regards to
embedding images (like on the bottom area) as well
as the most important one is whether I can use a
"box" for displaying text, like a paragraph. I
believe prawn offers similar support in this regard
but I never had a use case or need to group several
boxes into the same page (e. g. DIN A4, or even
smaller than that; the old gamebooks actually had
DIN A5 I think, or whatever is the smaller format,
DIN A1 is the largest if I recall off-hand).

Anyway, thank you for reading, and please do feel
free to close this issue request. I'll have a look
at it again in perhaps two or three weeks or so,
so don't worry, it's fine to close it.

(It may also be helpful for hexapdf if you look at
different use cases, so perhaps hexapdf could 
benefit from being able to satisfy such a use
case, but of course ultimately this is a selfish
request because I need such a functionality. :D
While I have a lot of legacy use cases for prawn,
I'd like to transition into hexapdf eventually
in the long run, so I'd rather want to use hexapdf
more. I'll have a more seriously look into hexapdf
again at a later time, but time is limited so I have
to spread it between different projects, some of
which are not related to computers too)

Also thank you in advance for reading this lengthy
issue here!

**Comment by gettalong** [comment]
Quite an interesting read and project! Will have to get a look at your gem! I have heard of DSA but more due to playing a bit of Ultima back in the day. Bookwise the only thing I can remember that would be similar are some of the special edition books for the [Knickerbocker Gang](https://de.wikipedia.org/wiki/Knickerbocker-Bande#Ratekrimis_und_Entscheidungsgeschichten) that I had.

So, back to your question and, yes, I think everything you need is already there, albeit maybe quite differently to use as with Prawn.

I think that the following code and resulting [gamebook.pdf](https://github.com/gettalong/hexapdf/files/9789870/gamebook.pdf) show more clearly what I mean. The code uses the `HexaPDF::Composer` class for this. We create a custom composer to define the "static" parts (header at the top and page number at the bottom) as well as the styles to use for the different text parts (paragraph header, paragraph, intra-link). The code then iterates over all stored paragraphs, outputting the paragraph header together with setting a named destination at that point,  then the paragraph text, marking up all numbers as intra-links.

What is not shown is embedding of images but HexaPDF supports embedding fixed-sized images into the text itself and placing images anywhere you like (statically - the dice - at the bottom together with the page number or next to the paragraph, with automatic text re-flowing, see https://hexapdf.gettalong.org/examples/column_box.html).

I will close the issue but feel free to re-open it if you still have questions.

~~~ ruby
require 'hexapdf'

class GamebookComposer < HexaPDF::Composer
  def initialize(**kwargs, &block)
    super(**kwargs, margin: 60, &nil)
    style(:base, font: 'Times', font_size: 10)
    style(:para, margin: [0, 0, 24], line_spacing: 1.2, align: :justify, position: :flow)
    style(:header, font: ['Times', variant: :bold], font_size: 16, padding: [0, 0, 5])
    style(:link, font: ['Times', variant: :bold])
    yield(self)
  end

  def new_page(*, **)
    super
    top = @frame.bottom + @frame.height + 10
    right = @frame.left + @frame.width
    canvas.fill_color('black').
      line(@frame.left, top, right, top).
      stroke
    canvas.font("Helvetica", size: 12).
      text("Eine Reise in den Tod", at: [right - 120, top + 5])
    canvas.text((page.index + 1).to_s, at: [right - 10, @frame.bottom - 12])
  end
end

Paragraph = Struct.new(:number, :text)

paragraphs = DATA.read.split(/\n\n/).map do |para|
  first, *rest = para.split(/\n/)
  Paragraph.new(first, rest.join(" "))
end

GamebookComposer.create('gamebook.pdf') do |composer|
  composer.box(:column, equal_height: false) do |column|
    paragraphs.each do |para|
      column.text(para.first, style: :header, overlays: [lambda do |canv, box|
        left, top = canv.graphics_state.ctm.evaluate(0, box.height)
        composer.document.destinations.create(:XYZ, composer.page, left: left, top: top, name: para.first)
      end])
      items = para.text.split(/(\d+)/).map.with_index do |part, index|
        if index.even?
          part
        else
          {text: part, style: :link, overlays: [[:link, dest: part]]}
        end
      end
      column.formatted_text(items, style: :para)
    end
  end
end

__END__
1
Ich weiß nicht, wie Sie darauf kommen, aber das
Abenteuer fängt nicht hier an. Versuchen Sie es mal in
Abschnitt 17, da haben Sie mehr Glück ...

2
Sie halten Sich nur kurz unter dem Gebüsch versteckt,
welches eine Mulde überzieht und beobachten streng
das Umland um Sicher zu gehen, daß sich niemand
böses Ihnen nähert. Dann, als die Dämmerung Praios'
Glanz vertilgt hat und Phex (auch hier ?) regiert
machen Sie sich auf den Weg. (27)

3
Sie hechten so schnell sie können hinter dem Mann
her, doch es ist gar nicht leicht ihn überhaupt ein
zukriegen, so getrieben ist er von den wahnsinnigen
Schmerzen. Doch in diesem Wahnsinn rennt er nicht
nur geradeaus (wobei er mit Sicherheit bald ins Wasser
stürzen würde), sondern schlägt Haken und bleibt
kurzzeitig an einem Fleck. Ergreifen Sie Ihre Chance in
Abschnitt 77.

4
Frencar von Dorenhain ist am Ende. Seine
zerschmetterte Rüstung konnte den von Ihnen
geführten Schlag nicht mehr abfangen und nun kniet er
vor Ihnen, mit einer klaffenden Wunde und fleht um
Gnade. Die nun handelt sind nicht Sie , sondern die
Macht in Ihnen. "Dein Platz ist nicht in meinen Hallen"
hören Sie sich sagen als sie mit Leichtigkeit die Waffe
auf ihn niederfahren lassen. Die Wucht des Schlages
spaltet Seinen Schädel, seinen Körper und die Erde
unter ihm, die sich auftut und ihn verschlingt. Wenige
Augenblicke später ist alles vorbei. Auch Sie sinken
auf ihre Knie und spüren, wie die Kraft Rondra's sie
wieder verlässt. Niemals werden Sie dieses Gefühl
vergessen. (166)

5
Das gegnerische Schiff brennt ! Dies ist ein großer Sieg
für Sie, doch er ist noch nicht besiegelt. Warum
erfahren Sie bei Abschnitt 52.

6
Sie haben sich dafür entschieden, hier stehen zu
bleiben, und der Gefahr, ganz rondrianisch
entgegenzutreten. Natürlich steigen Sie auch vom Pferd
ab und nehmen Ihre Lieblingswaffe fest in die Hand.
Die Schritte kommen immer näher, gleich kommen die
Orks um das Buschwerk drum herum und werden Sie
sehen. Lesen Sie Abschnitt 216.

7
Das ist ein sehr langer Weg, den Sie sich da vornehmen
wollen. Da Sie die meiste Zeit durch das relativ sichere
Mittelreich und über befestigte Reichsstraßen wandern
können haben Sie eine vermutlich angenehme Reise
vor sich. Aber wenn Sie einmal die Grenzen des
Herzogtums Weiden verlassen, dann haben sie es in
den Sichelgebirgen mit Orks und Goblins, der
Witterung und vielleicht schlimmeren zu tun.
Vielleicht ist es da doch besser, einen kürzeren Weg zu
wählen, wo dieser doch auch nicht einfach und sicher
werden wird. (31).

8
Nachdem Sie den letzten Bissen Ihrer Mahlzeit unten
haben, werden Sie wieder geknebelt. Da Ihnen klar ist,
daß ein Aufpasser nicht weit sein kann, ist es auch
unnötig, sich zu überlegen, wie Sie nun wieder weg
kommen können. Nach einiger Zeit sind sie schon sehr
müde und schlafen bald ein. Da hören Sie, daß eine
weitere Person gekommen sein muß. An dem
aufgeregten Gerede erkennen Sie, daß es ein erwarteter
Gast sein mußte, von dem man sich etwas erhofft.
Wollen Sie versuchen zu verstehen, um was es geht
(303), oder lieber schlafen, um Ihre Kräfte für einen
neuen Fluchtversuch (162) zu sparen ?

9
Sie steigen wieder auf das Pferd und reiten noch ein
paar Meilen. Doch nicht nur Ihnen sondern auch dem
Tier merkt man die Müdigkeit an. Weit kommen Sie
auf diese Weise nicht. Bald sind sie übermüdet und
suchen sich abseits des Weges ein sicheres Plätzchen
hinter einem Gebüsch (165).

10
In Festum wenden Sie sich an den örtlichen
Rondratempel, in dem Sie eine neue Ausrüstung
erhalten. Nicht nur Norgat, sondern auch noch eine
junge Novizin wollen von hier aus zurück nach
Perricum, so daß sie nicht nur eine Heimreise in
Gesellschaft, sondern auch deutlich weniger
gefahrvolle Reise haben werden. Außerdem wird
veranlasst, daß alle Geweihten, die sich an der
Verschwörung um Ihren Besitzt beteiligt haben,
ergriffen werden sollen, sobald man Ihrer Habhaft
werden kann. Sie aber machen Sich auf die Heimreise
in Abschnitt 263.

11
Sie sehen einen mit bunten Fahnen und Wimpeln
bestückten großen Leiterwagen, der Fässer und allerlei
Kisten geladen hat. An den Zügeln, die bei zwei
struppigen Pferden enden, sitzt ein kahlköpfiger Mann,
dem die Haare, die ihm auf dem Kopf fehlen allesamt
in dem mächtigen Bart hängen. "Prächtiger als ein
Zwergenbart" denken Sie, aber bei diesem Mann
handelt es sich um einen Menschen. Wollen Sie den
Kerl so schnell es geht töten (120) damit Sie
ungehindert weiter kommen, oder sich lieber als
Freund zu erkennen geben (243) ?

12
Sind es schon Stunden oder Jahre ? Immer noch sitzen
Sie hier, kalt, naß und wahrscheinlich krank. Ihre Füße
und Hände spüren Sie nicht mehr. Sinnlos sich
Gedanken zu machen ob Ihre Hände gefesselt sind.
Wieder überkommt Sie die Ohnmacht ... ( 298)

13
In ihrer Verzweiflung wenden Sie sich an die einzige,
die Ihnen noch helfen kann. "Herrin Rondra !"
beginnen Sie Ihr Gebet, "Ich habe versucht, ihm
Einhalt zu gebieten, aber das einzige was ich jetzt noch
habe ist die Ehre, die ich im Kampf nicht verlieren will
auch wenn ich kaum lebend in ihn gehen muß. Ich
vertraue auf Dich, daß Du mein Schwert leitest, daß
Deine Gerechtigkeit triumphieren wird über die
Niedertracht derer, die vorgeben, dies in Deinem
Namen zu tun." (240)

14
Was war das ? Ein Geräusch hat sie aus schönen
Träumen von ehrenvollen (und siegreichen) Kämpfen
gerissen. Vorsichtig, ohne ein Geräusch zu machen,
bewegen Sie sich in eine Position, in der Sie die
Richtung beobachten können, aus der Sie das Geräusch
hörten - und tatsächlich. Ein paar finstere Gestalten
schleichen in direkt unnatürlicher Körperhaltung daher.
Sie scheinen nicht bewaffnet, aber schnüffelnde und
scharrende Geräusche verraten Ihnen, daß dies keine
armen Wanderer sind. Ist es wirklich das, was Sie
befürchten und nun froh sind, daß Sie sich gut
versteckt haben ? Ja, so leid es uns tut, sie haben drei
Zombies entdeckt, die, wie so vieles anderes in diesem
Land, das Leben der Menschen dem in den
Niederhöllen so ähnlich wie möglich machen. Wollen
Sie hoffen, daß die Zombies Sie in ihrem guten
Versteck nicht finden (74) oder einen Präventivschlag
unternehmen und die Kreaturen angreifen ( 75) ?

15
Zu ruhig. Eben noch war das Plätschern des Wassers
deutlich zu hören, auch das Stampfen von so manchem
Matrosenfuß war bisher ein stetiger Begleiter in dieser
Nacht, doch jetzt ist dort nichts. Haben Sie das Gefühl
es kommt etwas grauenhaftes aus den tiefen des
Wassers auf Sie zu und Sie sollten lieber mal
nachschauen, ob es Arbeit für eine Kriegerin gibt
(281), oder wollen Sie lieber weiter schlafen - froh
sein, daß endlich mal kein Radau ist (117).

16
Der strahlende Sonnenschein (von dem Sie gar nicht
wissen, wo der plötzlich her kommt) bestärkt sie in
dem Glauben, daß es richtig war, dem Befehl zu
gehorchen. Sie trällern ein Liedchen, daß sie von
irgendeinem singenden Thorwaler aufgeschnappt
haben und treiben damit Ihr Pferd an, sich in schnellem
Schritt auf die Hafenstadt zu zu bewegen. Bei Meile 99
sitzt jemand am Straßenrand.

17
Es könnte so ein schönes Wetter sein - aber nein - der
Herr Efferd scheint kleine Rondrageweihte nicht
sonderlich zu mögen. Wenigstens ein Trost, daß die
Felder so nicht vertrocknen und die Ernte in diesem
Jahr gut zu werden verspricht, denn auch eine
Geweihte lebt nicht vom Wort der Götter allein. Sie
wissen schon nicht mehr, was mehr auf ihrer Haut
klebt, das weiße Gewand mit dem roten Löwenkopf
oder die Rüstung, die sie darunter tragen. Eigentlich
hätten sie nicht schlecht Lust sie auszuziehen, aber
alleine wie sie nun einmal unterwegs sind, wäre es
unklug, Räubern oder noch schlimmeren nackt in die
Arme zu rennen - und eigentlich wärmt ja selbst die
Rüstung ein bisschen. Ja, schlimmer noch als eine
ganze Räuberbande könnte es tatsächlich kommen,
auch wenn die Chancen nicht schlecht stehen,
Rommilys im laufe des morgigen Tages unbeschadet
zu erreichen, aber auf der anderen Seite des Gebirges,
dessen Ausläufer ganz in Ihrer Nähe liegen, befindet
sich die Warunkei, das Reich des schwarzen Drachen,
eines der schrecklichsten Länder, die es - nicht nur -
auf diesem Kontinent gibt. Was sie davon wissen ist
nur Gerüchteweise, aber auch wenn Mut zu ihren
Tugenden gehört, sie hätten keine Rechte Lust darauf,
dort einmal hin zu gehen um den Wahrheitsgehalt der
Geschichten zu überprüfen. Während Sie sich mit
diesen Gedanken vom Nieselregen ablenken taucht vor
Ihnen ein Gebäude auf, in dessen Fenster Sie Licht
sehen. Treten Sie näher in Abschnitt 140.

18
Nichts gegen Ihr Pflichtbewußtsein, aber wenn Sie sich
die Blaue Keuche holen, ist niemandem gedient !
Wollen Sie nicht doch lieber die Nacht in der Herberge
verbringen (178) oder in dem wieder stärker
werdenden Regen weiter reiten (17) ?

19
"Guten Morgen, Werte Dienerin der Göttin" begrüßt er
Sie ein wenig zu schleimig für Ihren Geschmack. Er
hält euch eine Rolle Papier hin, die ein rotes Siegel
trägt. Dieses Siegel zeigt eine Löwin. "Es war soeben
ein Bote hier, der sagte dies sei für euch. Ich bot ihm
an auf euch zu warten oder euch sogar zu wecken,
jedoch hatte er es eilig und wollte schnell weiter." Sie
nehmen den Brief entgegen. Wollen Sie den Brief
öffnen (232) oder nachsehen, ob der Bote draußen noch
zu finden ist (160) ?

20
Die Schiffsreparaturen gehen gut voran. Es werden die
Segel geflickt, die Seile repariert, die Reling
ausgebessert und - ganz wichtig, der Rumpf auf
eventuelle Schäden hin überprüft. Der Reest des Tages
wird damit verbracht, aber gegen Abend ist wieder
alles in Ordnung, so daß die "Schneller Walsach"
wieder fahrt aufnehmen kann. Wollen Sie lieber früh
schlafen gehen (58), oder freiwillig Wache halten
(226), weil Sie der Ruhe auf See nicht trauen und
ohnehin kein Auge zumachen könnten ?
~~~
