### ISSUE TITLE
Advice related to dimensions 

### ISSUE THREAD

**Issue by earthlingworks** [gettalong/hexapdf#204]
Recently we've gotten a couple of PDFs that have been cut off and items placed in the wrong place because of the source PDFs (from different people) have had strange dimensions.

All files have come from Adobe PageMaker and when you open them in Acrobat or other PDF viewers they look fine.

We run pdfinfo -box and see something like this: https://share.getcloudapp.com/bLu5PkD4

Looks like the issue we're running into is because the mediabox is very different than the other dimensions. Seems like viewers typically use cropbox dimensions? Some of these files are government state files and we can't tell our users to fix the source files because that would actually have to be done by the US state which you can imagine isn't going to happen.

Most PDFs we've looked at have dimensions that match across all box types. So questions is: would it be a bad idea to use cropbox instead? I'm guessing we'd be able to do this with hexpdf but not sure if this would end up with us experiencing other potential issues. 

I understand this is a weird one so just looking for any thoughts/advice you might have related to this. Thanks!

**Comment by gettalong** [comment]
The PDF specification in section 14.11.2 describes the various page boundaries (media box, crop box, bleed box, trim box and art box), how they relate to each other and what they are used for.

So having different values for the media and crop boxes is something not that unusual. The thing is that it depends on the use-case which box is used.

For example, when using `HexaPDF::Type::Page#canvas` the origin is translated to coincide with the lower-left corner of the media box. When using `HexaPDF::Type::Page#to_form_xobject` the bounding box of the created Form XObject is based on the crop box.

What are you doing where the results are not what you expect?

**Comment by earthlingworks** [comment]
Good question. I'll have to ask the team and will have an answer on Monday. Thanks!

**Comment by earthlingworks** [comment]
Yep, so looks like we're getting media box with HexaPDF::Type::Page#canvas. Viewers seem to rely more on crop box for display (which is basically what we do + overlay data) so it might make sense for us to use that as well.

**Comment by gettalong** [comment]
Thanks for getting back to me! The current implementation uses the media box to translate the origin and this is hard-coded.  What I could introduce is a keyword argument that prevents this automatic translation so that the origin stays at (0,0) and one can then translate as one sees fit. Would that help your use-case?

If you'd like, you could also (privately) provide the PDF in question and some (pseudo)code of what you are doing so that I could have a look at it.

**Comment by gettalong** [comment]
> Yep, so looks like we're getting media box with HexaPDF::Type::Page#canvas. Viewers seem to rely more on crop box for display (which is basically what we do + overlay data) so it might make sense for us to use that as well.

The spec in 14.11.2 says regarding the crop box: *"The crop box defines the region to which the contents of the page shall be clipped (cropped) when displayed or printed. "*

I've tried a few things and you are absolutely correct, when viewing the crop box and not the media box is used in all viewers I tried. I have to say I'm a bit embarrassed that I didn't notice this in the last 8 years... :disappointed: 

So I will make two changes:

* Move to using the crop box instead of the media box by default for the origin translation in the #canvas method.
* Allow skipping the origin translation completely.

**Comment by earthlingworks** [comment]
Thanks for following up so quickly. That's great to hear about the upcoming changes :)

It's tricky and easy to miss the media/crop box thing in that we've had many documents from all types of sources uploaded and processed and 99.9% all worked great with the current approach.

**Comment by earthlingworks** [comment]
Following up here with more details that we also use this to get page dimensions. Would this also default to crop box dimensions? ```HexaPDF::Type::Page#box```

**Comment by gettalong** [comment]
Yes, that will also default to the crop box since tests show that if a crop box is set the viewers all use the crop box for display *and* for page dimensions.

**Comment by gettalong** [comment]
@earthlingworks I have pushed the needed changes to the devel branch. It would be great if you could try them out and let me know whether that fixes your issues.

**Comment by earthlingworks** [comment]
Great! I'll do that when I get a chance later today and get back to you on it, thanks!

**Comment by earthlingworks** [comment]
Actually, someone on the team was still around and they checked it out. Everything works perfectly now, even a previous file we had issues with on the layout side. So all looks good!

**Comment by gettalong** [comment]
Thanks for the feedback! Although this seems to be a rather easy change, it can have a vast impact, so thanks for testing this out!
