### ISSUE TITLE
ArgumentError of "utc_offset out of range"

### ISSUE THREAD

**Issue by earthlingworks** [gettalong/hexapdf#224]
Hey Thomas, we're seeing an ArgumentError on a PDF when `optimize: true` and the message is "utc_offset out of range".

Script to reproduce: 

```require 'hexapdf'
require 'down'
file = File.open(ARGV[0])
output_pdf = HexaPDF::Document.new(io: file)
​
output_pdf.write('outpt.pdf', validate: false) ```

I'll send the PDF through email to keep its contents private. Thanks!

**Comment by gettalong** [comment]
Thanks for the file! It contains timestamps like the following which are invalid:

~~~
D:20221215215639-76'00'
D:20221215215642-76'128'
~~~

Those timestamps are invalid 1) because of the trailing apostrophe and 2) because the time zone offset values for hours and minutes are not within 0-23 and 0-59 respectively.

The first error is already handled but not the second, so I will implement a work-around.

**Comment by earthlingworks** [comment]
Great. Thanks for the update!

**Comment by gettalong** [comment]
Fix is already implemented, will be in the next released.
