### ISSUE TITLE
Editable PDF Form Fields Not Autosizing Text

### ISSUE THREAD

**Issue by Gavin-FDI** [gettalong/hexapdf#256]
I am using HexaPDF AcroForm to apply text into PDF form fields. Many of these form fields have the text size set to auto so when I manually text in text it will be auto-sized. However, for whatever reason the text that is added through HexaPDF often remains too big. Is there anything that can be done to resolve this issue programmatically? 

Example Code:
```
pdf = HexaPDF::Document.open(pdf_path)
pdf.acro_form.field_by_name('thing_1').field_value = 'Lorem ipsum dolor sit amet.'
pdf.acro_form.field_by_name('thing_2').field_value = 'Sed do eiusmod tempor.'
```

Example PDF:
[Test.pdf](https://github.com/gettalong/hexapdf/files/12177706/Test.pdf)

Result through HexaPDF:

![image](https://github.com/gettalong/hexapdf/assets/83421012/98ee5e75-0e34-46d8-8955-8947c056a39c)

Result through manually typing into PDF:

<img width="935" alt="image" src="https://github.com/gettalong/hexapdf/assets/83421012/fddbee0e-213e-417e-b95e-a4cdc4fe53b6">

**Comment by gettalong** [comment]
Thanks for reporting! Could you please provide the PDF in question and, if easily possible, a small script that shows the problem?

**Comment by Gavin-FDI** [comment]
> Thanks for reporting! Could you please provide the PDF in question and, if easily possible, a small script that shows the problem?

@gettalong Unfortunately I cannot share our actual PDFs and code but I have updated my original comment with more information using example PDF/code.

**Comment by gettalong** [comment]
@Gavin-FDI Thanks for the PDF - I can reproduce the problem.

So the sample PDF you provided has a `/DA` value of `/Helv 0 Tf 0 g` which means it uses the font Helvetica with font size 0 and text color black. Using font size 0 is what is called "auto-sizing" and the PDF spec has to say this about it:

> A zero value for size means that the font shall be auto-sized: its size shall be computed as an implementation dependent function.

The current implementation dependent function for auto-sizing in HexaPDF depends on whether the area (rectangle) of the text field has a height of 0 or not. If it has a height of zero, it uses a fixed value via the configuration option `acro_form.default_font_size` which defaults to 10. Otherwise it calculates the font size based on the height of the text field but doesn't use the width.

Since this implementation doesn't reflect the expectation most users will have, I will see how to change it so that the width will also be taken into account.

**Comment by gettalong** [comment]
@Gavin-FDI I have changed the implementation to also take a field widget's width into account when auto-sizing: 
![image](https://github.com/gettalong/hexapdf/assets/4104/73c1613d-2076-4432-a16f-295a9c44c666)

The change is available on the devel branch if you want to test it out.

**Comment by Gavin-FDI** [comment]
@gettalong Thanks, I confirmed that this is working now!
