### ISSUE TITLE
Is it possible to split out individual pages from multiple files and use them to create a new file?

### ISSUE THREAD

**Issue by Ada323** [gettalong/hexapdf#26]
Hello,

I'm trying to create a new PDF out of selected pages from multiple other PDFs. Your merge functionality works beautifully but ideally I'd really like to be able to split out pages and merge them without having to manually download them and use a desktop tool for the page extraction part. Do you support this functionality? I wasn't able to find it in your docs but I wanted to double check. 

Thank you!

**Comment by gettalong** [comment]
If I understand your question correctly, you want to merge multiple PDFs but not all pages from those PDFs, only some.

The `hexapdf merge` command allows using the `--pages` option after each PDF that should be merged, using only those pages that are specified.

For example, if you want to merge pages 1, 3 to 7, and 10 from `a.pdf` and pages 2, 4, 6 to 10 from `b.pdf` you would invoke the hexapdf binary like this:

~~~ shell
$ hexapdf merge a.pdf --pages 1,3-7,10 b.pdf --pages 2,4,6-10 out.pdf
~~~

Is this what you are looking for? If not, could you add more details to your question?

**Comment by Ada323** [comment]
That's exactly what I was looking for - thank you so much!

**Comment by Ada323** [comment]
That works perfectly in the terminal but I'm having difficulty executing the same command within a ruby file. I suspect it's just a syntax issue but if you could please give me an example of how to do this in the library context I would very much appreciate it. Thank you again!

**Comment by gettalong** [comment]
Have a look at the [simple PDF merging example](https://hexapdf.gettalong.org/examples/merging.html). However, the code for the `hexapdf merge` command is a bit more involved since it does a bit more, for example, removing unnecessary PDF objects.

If you post your code, I could have a look at it.

**Comment by Ada323** [comment]
Cool, thank you. I did use the simple merging example code from the docs as inspiration though as you said it becomes more complicated when taking page specifications into account. I've posted my code below - the test_hash variable is hard coded right now but that data will eventually be passed in based on user input. I'm relatively new to ruby (so far my professional experience has mostly been with javascript), so if you have any suggestions to improve this I'd love to hear them.

```ruby
require 'hexapdf'

test_hash = {
	'degas-the-dancers.pdf' => [100, 103],
	'art-of-paul-gauguin.pdf' => [0, 2],
	'jan-steen-painter-and-storyteller.pdf' => [59, 75, 122],
	'gods-saints-and-heroes.pdf' => [13, 18, 200]
}

target = HexaPDF::Document.new
test_hash.each do |file, target_pages|
	  pdf = HexaPDF::Document.open(file)
	    pdf.pages.each_with_index do |page, index| 
	    	if target_pages.include?(index)
	    		target.pages << target.import(page)
	    	end
	    end
end
target.write("test.pdf", optimize: true)
```

**Comment by gettalong** [comment]
Welcome to Ruby! :smile: It had its 25th birthday yesterday.

As for your code: It actually looks quite good, however:

* It seems that you are mixing spaces and tabs for indentation. I would suggest *always* using two spaces for indentation. So, for example, the contents of `test_hash` should be indented two spaces as well as each block level (e.g. `do ... end`). This can be made easier by using a tool such as [Rubocop](https://github.com/bbatsov/rubocop). Just be aware that there is *no one* style that all Ruby programmers use and treat the [style guide](https://github.com/bbatsov/ruby-style-guide) as a suggestion. For example, I prefer somewhat different settings (see https://github.com/gettalong/hexapdf/blob/master/.rubocop.yml). If you contribute to some Ruby repository without a tool enforcing a certain style, just have a look at the existing code and follow the spirit.

* The code already looks quite Rubyish, so no changes in this regard :+1:. However, runtime-wise it might not be the best solution. If you expect that not all pages from each PDF are taken, it would be better to iterate with `target_pages.each` using `pdf.pages.page(index)` inside the loop, and not `pdf.pages.each_with_index`. This would lead, for example, to a loop with three iterations for  `'gods-saints-and-heroes.pdf' => [13, 18, 200]` instead of at least two hundred, and the need for checking  `target_pages.include?(...)`, removing an `O(n)` operation. You would need to check for the existence of the page though.

**Comment by gettalong** [comment]
:+1: Yes, I think that looks better.

However, inside `target_pages.each do |page|` you should also check whether the page actually exists before importing and adding it because otherwise an empty page is added (see https://hexapdf.gettalong.org/api/HexaPDF/Type/PageTreeNode.html#method-i-insert_page). I.e. 

~~~ ruby
test_hash.each do |file, target_pages|
  pdf = HexaPDF::Document.open(file)
  target_pages.each do |page|
    page = pdf.pages[page]
    target.pages << target.import(page) if page
  end
end
~~~

And: No problem, if you need anything else feel free to ask.

**Comment by Ada323** [comment]
Awesome, thank you!!
