### ISSUE TITLE
Dealing with page rotation

### ISSUE THREAD

**Issue by brettwgreen** [gettalong/hexapdf#264]
I've got this PDF that I'm trying to draw a box on... all of my box coordinates are determined based on orientation of the page as viewed by the user just looking at the document.

However, I've got this one page that has `[:Rotate] = 90` that's killing me mentally. I managed to translate and draw the box correctly myself by doing math on the coordinates but feel like there must be an easier way especially when I encounter other degrees of rotation.

Is there a way to do something to work with the page as if it was oriented correctly with (x, y) being bottom left of the page as its seen in a viewer? Because then the next problem I had was adding text on 'top' of the box which, of course, instead of rendering ther way I expected... it read from top to bottom (like, tilt your head to the right to read it).

I tried variations of, for example:

```
canvas.rotate(-90) do
  box.draw(canvas, lower_left_x, lower_left_y)
end
```

The last page of the attached document has the rotated page.
[sample_doc.pdf](https://github.com/gettalong/hexapdf/files/12651932/sample_doc.pdf)

**Update:** A little bit better code example... Here I try and draw two rectangles using method kinda documented here:
https://hexapdf.gettalong.org/documentation/api/HexaPDF/Content/Canvas.html#method-i-rotate

```ruby
def draw_boxes
  file = "/Users/brett/Documents/sample_doc.pdf"
  out = "/Users/brett/Documents/sample_doc_boxes.pdf"
  doc = HexaPDF::Document.open(file)
  page = doc.pages[doc.pages.count-1]
  rectangle = [300, 400, 100, 50] 
  canvas = page.canvas(type: :overlay)
  canvas.stroke_color('red').rectangle(*rectangle).stroke
  canvas.rotate(90) do
    canvas.stroke_color('purple').rectangle(*rectangle).stroke
  end
  doc.write(out)
end
```

When I run this code I ONLY see the red rectangle... the purple disappears or is drawn outside the boundary of the page or something. In any case, I only see one rectangle.

**Comment by gettalong** [comment]
The /Rotate key of a page is - more or less - only for viewing a PDF. When a PDF viewer sees that key it draws the content as it normally would but rotates the result. So the content of the page is always drawn inside the crop box of the page as defined by the /CropBox key (or /MediaBox key if the former doesn't exist), *without* the rotation. And only afterwards rotated.

You can think of the /Rotate key of an easy way for a PDF processor to rotate a page without touching the content of the page itself.

What you could do is to incorporate the /Rotate key information into the content stream and then drawing the boxes. This can be done with the [`Page#rotate`](https://hexapdf.gettalong.org/documentation/api/HexaPDF/Type/Page.html#method-i-rotate) method, i.e.

~~~ ruby
doc = HexaPDF::Document.open(file)
page = doc.pages[doc.pages.count - 1]
page.rotate(0, flatten: true)
canvas = ...
~~~

Since you don't want to add an additional rotation, you would choose `0` for the rotation angle and with `flatten: true` you specify that /Rotate key should be removed and the information incorporated into the page content.

Does this help?

**Comment by brettwgreen** [comment]
Just understanding it helps at the very least, so thank you.

Sounds like you're saying to rotate the page "for real" and remove the viewer-only rotation key by using 'flatten'. I can try that tomorrow as that will probably work for my needs and simplify things... does that actually then change the page dimensions and origin to essentially match the viewer perspective?

**Comment by gettalong** [comment]
Yes, that will adjust all page boxes (media, crop, art, ...), the page content stream as well as all annotations so that they all take the rotation into account.

**Comment by brettwgreen** [comment]
That worked perfectly for what I'm trying to do. Now just help me understand what `page.rotate(0)` means? Instinctually, it reads like it won't rotate at all... i.e. 'rotate zero degrees'?!? When in actuality it seems to rotate counterclockwise 90 degrees. That's a bit confusing.

Trying to generalize the code... should it always be `page.rotate(0, flatten: false)` regardless of Page[:Rotate] key? Or should it be like `page.rotate(page[:Rotate]-90, flatten: true) if page[:Rotate].present?`
