### ISSUE TITLE
Background image

### ISSUE THREAD

**Issue by lionel218** [gettalong/hexapdf#28]
Hi @gettalong , Can we use background image on hexapdf?
I'd like to add background image and overwrite a text as like attached pdf file.
[207 Sanderling Ln - JSP.pdf](https://github.com/gettalong/hexapdf/files/1860957/207.Sanderling.Ln.-.JSP.pdf)
It is possible with this gem?

**Comment by lionel218** [comment]
Thanks for your kindness @gettalong 
And can I use opacity for the background image?

**Comment by lionel218** [comment]
Hi @gettalong , can I modify the text content and background image for uploaded pdf?

**Comment by gettalong** [comment]
You will need to parse the contents of the page as described in my last comment. During the parsing (or later, if you save the results in an array) you need to determine which of the images is the background image. Then change the image reference in the `/Resources` -> /XObject` hash to the new image.

As for the text: There is currently no algorithm in HexaPDF for determining which characters form words and where these words are. So you would need to write that for yourself currently. Then, when you know that, remove the text remembering the position and insert the appropriate code for the new text.

This all may sound a bit complex because it is so. It will probably be easier if you just create a template PDF with some visual design tool and then use an underlay canvas for the background image and an overlay canvas for the text.

**Comment by gettalong** [comment]
@lionel218 I will close this issue now since it seems that your question was answered.

**Comment by lionel218** [comment]
OK
