### ISSUE TITLE
HexaPDF::Error (Validation error: Required field BaseFont is not set)

### ISSUE THREAD

**Issue by Phill** [gettalong/hexapdf#30]
Worked fine then suddenly I get this error:
`HexaPDF::Error (Validation error: Required field BaseFont is not set)`

Can't find anything about it.

Thanks!

**Comment by gettalong** [comment]
HexaPDF validates the PDF when writing it out so as to make sure it conforms better to the PDF standard. In the case of your error message, it seems that that the `BaseFont` key is not set for a font object. If you can provide the PDF in question I can have a look at it and see if this is a problem with HexaPDF or the file.

You can avoid validation by using setting the appropriate key on [HexaPDF::Document#write](https://hexapdf.gettalong.org/api/HexaPDF/Document/index.html#method-i-write).

Not doing validation when opening, modifying and then saving PDFs is fine in most cases. However, if you create a PDF with HexaPDF, validation should be done since it corrects some things that otherwise need to be done manually (for convenience' sakes).

**Comment by Phill** [comment]
Thanks for the info. I'm opening a supplied PDF and changing a few things then saving it as a new file. I think it's just this one PDF that has the issue so it's probably a broken PDF from the supplier.

How would I set a BaseFont in this case that it's missing?

**Comment by gettalong** [comment]
I *think* it is not quite easy to implement this 100% correctly because the BaseFont value would need to be adjusted based on the other values of the font in question.

For example, for Type1 fonts the value of BaseFont could be deduced from the font program if that is embedded.

However, since it is just the name of the font in question you could just set a dummy value and see if it works in some PDF viewers.

As for where to find the needed object: Each page object has a [#resources method](https://hexapdf.gettalong.org/api/HexaPDF/Type/Page.html#method-i-resources) which returns a [HexaPDF::Type::Resources](https://hexapdf.gettalong.org/api/HexaPDF/Type/Resources.html) object. This object can be treated as hash in some regards and you want to access the `:Font` key. This returns a hash of mappings from font resource name to font object. So iterate through each font object and set the `:BaseFont` value if it is not set.

**Comment by gettalong** [comment]
HexaPDF tries hard to keep the file size as small as possible. So depending on what you do it might be a problem with the input PDF but I can eliminate that HexaPDF does something wrong in such a case.

**Comment by gettalong** [comment]
@Phill While implementing the last of the simple PDF font types, Type 3 fonts, I found that they don't defined a `BaseFont` key. This means that HexaPDF currently throws an erroneous validation error when encountering Type 3 font objects but this is fixed with the newly added Type 3 font implementation.

What all this means is that your supplied PDF files may have been valid after all. You can check whether the PDF uses a Type 3 font using the "Properties" menu in most PDF viewer applications. If this is the case, your file is probably valid.

If the file size problem you mentioned is still occurring, please open a new issue with more information, e.g. a sample PDF file would be great.
