### ISSUE TITLE
multiple certificate

### ISSUE THREAD

**Issue by heruwaspodov** [gettalong/hexapdf#307]
hai mas @gettalong ~
I already implemented the multiple signatures using HexaPDF, but somehow the existing certificate is broken. I already guarded by validation the DOCMDP but it was passed (not detect the DOCMDP level). 
for the file may I send you via email directly?
thank you

**Comment by gettalong** [comment]
Thanks for providing the files!

So the original document was already signed and the signature valid. It has no DocMDP transformation method. This doesn't mean, however, that you can just add something and not invalidate the original signature. This, however, depends on the PDF viewer.

All PDF readers will show that all signatures are cryptographically fine. Some will show that all are still valid while others will complain that the original signature is now invalid due to added form fields.

To satisfy all PDF readers you should finalize the document before the first signature.

**Comment by WSPDV** [comment]
Hi @gettalong, how to check whether it is possible to add the new signature? if the DocMDP not the only flagging to add a new signature?
Thank you

**Comment by gettalong** [comment]
@WSPDV I'm not 100% sure, to be honest. You certainly need to check for DocMDP and if it is missing, assume that you can add another signature. As I have written, whether multiple signatures appear as valid also depends on the PDF viewer one is using. So I would try adding the signature and then viewing the result in the PDF reader of your choice to check.

**Comment by gettalong** [comment]
@heruwaspodov @WSPDV There will be a change in the upcoming release that fixes a problem with HexaPDF invalidating an existing signature. Maybe that helps in your cases too.
