### ISSUE TITLE
Unrecognized font error in Adobe Acrobat Reader after signing Chrome print PDF

### ISSUE THREAD

**Issue by omohokcoj** [gettalong/hexapdf#308]
[index.html.pdf](https://github.com/user-attachments/files/15856315/index.html.pdf)

```ruby
require 'hexapdf'
require HexaPDF.data_dir + '/cert/demo_cert.rb'

doc = HexaPDF::Document.new(io: File.open('index.html.pdf'))

doc.sign("signed.pdf",
         reason: 'Some reason',
         certificate: HexaPDF.demo_cert.cert,
         key: HexaPDF.demo_cert.key,
         certificate_chain: [HexaPDF.demo_cert.sub_ca,
                             HexaPDF.demo_cert.root_ca])

```

![image](https://github.com/gettalong/hexapdf/assets/5418788/2abf645f-49f2-472e-b2df-d8106c8d01c3)

Signing this PDF generated using Chrome Print feature causes 'Cannot extract the embedded font error' in Adobe.
Modifying the document and saving a new revision doesn't result in an error.

**Comment by gettalong** [comment]
Thanks for reporting!

I tried to reproduce the error but failed. My steps were:

1. Download the linked file.
2. Add the code in the issue description to a file.
3. Run the file with HexaPDF 0.44.0.
4. Open the generated `signed.pdf` in Adobe Reader on Windows.

The file opens fine in Adobe Reader without any error. Selecting and copying the text also works without problems.

Inspecting the generated `signed.pdf` shows only one potentially significant difference that is related to the error. The font descriptor object for the font has the /Descent value corrected from 250 to -250 since the PDF spec mandates that the value needs to be negative.

Could you provide the `signed.pdf` that shows this error?

**Comment by omohokcoj** [comment]
@gettalong thanks for the quick reply!

[signed.pdf](https://github.com/user-attachments/files/15857241/signed.pdf)

I'm using Adobe Reader on Mac:
![image](https://github.com/gettalong/hexapdf/assets/5418788/787a34c9-f946-45ad-a2a9-95f30f892ca1)
![image](https://github.com/gettalong/hexapdf/assets/5418788/746d95a5-bf8d-4f03-b6cc-aeca699f9dbb)

**Comment by gettalong** [comment]
Thanks for the PDF! Alas, it doesn't show as invalid for me with Reader 2024.001
![image](https://github.com/gettalong/hexapdf/assets/4104/4cff6a67-dee9-448b-b018-1390a8199b7f)

Could you update to the latest reader on macOS and try again?

**Comment by gettalong** [comment]
@omohokcoj Could you try the following file [signed.pdf](https://github.com/user-attachments/files/15857281/signed.pdf)? It was generated using `write_options: {validate: false}` which doesn't modify the font descriptor.

**Comment by omohokcoj** [comment]
@gettalong i've updated the the latest version of adobe and now the error is gone.
some users also reported this error on older version - but hopefully they can update the Adobe app soon

**Comment by gettalong** [comment]
@omohokcoj Thanks for the feedback! You could also try the file from https://github.com/gettalong/hexapdf/issues/308#issuecomment-2171361630 that was generated without the validation on the older Reader version.
