### ISSUE TITLE
Annotations example

### ISSUE THREAD

**Issue by ViktorKopychko** [gettalong/hexapdf#32]
Hello!
Could you please provide an example/sample code of adding the annotations to existing pdf?
Thank you in advance.

**Comment by gettalong** [comment]
There is currently on *some* convenience support for annotations. This means that you would need to read the PDF spec in order to determine which objects and attributes to add so that annotations work correctly. You can grab a copy of the PDF 1.7 spec for free at Adobe's site and have a look at section 12.5 which describes annotations. This section is somewhat easier to read in comparison to some other parts of the spec.

Please note that for some annotations you would need to determine a rectangular area to anchor an annotation. This is needed, for example, for link annotations.

Here is an example on how you could add link annotations to an existing document on each page at an arbitrarily chosen location of [100, 100] (from bottom left):

~~~ ruby
require 'hexapdf'

HexaPDF::Document.open(ARGV[0]) do |doc|
  doc.pages.each do |page|
    page[:Annots] ||= []
    page[:Annots] << doc.add(Type: :Annot, Subtype: :Link, Rect: [100, 100, 200, 200],
                             A: {Type: :Action, S: :URI, URI: 'https://hexapdf.gettalong.org'})
  end
  doc.write(ARGV[1])
end
~~~

**Comment by ViktorKopychko** [comment]
Thanks a lot for the response. Probably this should be added to the examples

**Comment by vlaew** [comment]
Hello!
I'm trying to implement adding FreeText annotations to an existing PDF:
```ruby
annotation = page.document.add(
  Type:     :Annot,
  Subtype:  :FreeText,
  Contents: 'annotation text',
  Rect:     [100, 100, 500, 200],
  DA:       '/F13 32 Tf'
)
page[:Annots] ||= []
page[:Annots] << annotation
```

But there's no annotation in the resulting document. If I change Subtype to `Text` then annotations are visible in the document.
According to spec 12.5.6.6 the key `DA` is required, so I think it's because of it, can't figure out what it should be.

Thank you in advance.

**Comment by gettalong** [comment]
The annotation itself *is* there but there is no visible appearance associated with it, so nothing is visible. The `/DA` key specifies the default appearance string that is used to regenerate the appearance of the free text annotation if the user changes the text. It needs to refer, at least, to a valid font object and font size. Also have a look at the `/AP` key of the annotation, spec 12.5.2. And it may depend on the PDF viewer. Have you tried opening the PDF in Adobe Reader?

Free text annotation are not yet implemented in HexaPDF, meaning you *can* do it but you have to do everything yourself, manually. Since the appearance generation of free text annotations is similar to text form fields, adding support for this shouldn't be too much effort. I have put in on my todo list for one of the next releases.

**Comment by vlaew** [comment]
>  Have you tried opening the PDF in Adobe Reader?

No, I haven't checked the document in Adobe Reader.

> Also have a look at the /AP key of the annotation, spec 12.5.2.

Thanks for the advice, I will check the spec.

Thank you for HexaPDF and a quick response!
