### ISSUE TITLE
Transparent Fields

### ISSUE THREAD

**Issue by cw6365** [gettalong/hexapdf#325]
Is there a way to create transparent widget fields, i see the colour chart at HexaPDF::Content::ColorSpace but can't see a transparent option. I want to programatically fill in the fields from our app.

Thanks

**Comment by gettalong** [comment]
Could you please describe a bit more what you want to do as I'm not sure where exactly the problem is?

Some general information: When you fill in a field using `field.field_value = ...`, HexaPDF uses an appearance generator class to generate the visual representation of the field value for the associated widgets. So there is no way to customize this behaviour except by creating a subclass of the appearance generator and telling HexaPDF to use that via the configuration option 'acro_form.appearance_generator'.
