### ISSUE TITLE
Opening and saving a digitally signed document changes the bytes

### ISSUE THREAD

**Issue by cw6365** [gettalong/hexapdf#328]
I have an existing digitally signed doc created with hexapdf.. it has one field DocMDP set to form filling..

<img width="1148" alt="Screenshot 2024-09-13 at 11 16 06" src="https://github.com/user-attachments/assets/ca665aa5-1f02-4d46-9eb8-b274f46d154f">

[signed-detatched.pdf](https://github.com/user-attachments/files/16992373/signed-detatched.pdf)

I'm trying to programatically fill in the field and add another signature.. but when i do the first signature becomes invalid.

I've stripped this back to simply opening the doc and re-saving it but this again changes the existing bytes so the signature is no long at the byteArray positions and becomes invalid..

<img width="1182" alt="Screenshot 2024-09-13 at 11 13 12" src="https://github.com/user-attachments/assets/7cad3cfc-5b07-4d3b-9536-4c60bc81a3d2">

[modified-three.pdf](https://github.com/user-attachments/files/16992414/modified-three.pdf)

I've tried with different write_options but no luck

```
doc = HexaPDF::Document.open("#{Dir.pwd}/spec/support/assets/signed-detatched.pdf")

doc.write('modified-three.pdf', incremental: false, validate: false, update_fields: false, optimize: false )
```

**Comment by cw6365** [comment]
OK.. so it seems to change the pdf version from 1.4 to 2.0. Is there anyway to stop this?

**Comment by cw6365** [comment]
It seems to be when you open a pdf it auto converts it to pdf 2.0, and you cannot convert it back or keep the original version?

```
[10] pry("./bin/console")> doc = HexaPDF::Document.open("#{Dir.pwd}/post-signed.pdf")
=> <HexaPDF::Document:3340>
[11] pry("./bin/console")> doc.version
=> "2.0"
[12] pry("./bin/console")> doc.version = '1.4'
=> "1.4"
[13] pry("./bin/console")> doc.version
=> "2.0"
```

**Comment by gettalong** [comment]
If you open a signed document, you always have to write it with `incremental: true`. Otherwise the initial signature(s) will become invalid because HexaPDF will rewrite the *whole* PDF instead of just the changes.

The version you get back from `Document#version` is either the set version or the one from the catalog's `/Version` entry, whichever is greater. I assume that `post-signed.pdf` has the `/Version` entry set to 2.0 and so that is returned (also see the [api description of the method](https://hexapdf.gettalong.org/documentation/api/HexaPDF/Document/#method-i-version).

When initially signing with HexaPDF, the version should have been set to 2.0 since `ETSI.CAdES.detached` is only available in PDF 2.0. I will look into that.

**Comment by gettalong** [comment]
@cw6365 I have updated the devel branch on Github to include a change that should fix the problem with 2.0. Could you try with that branch to see if it fixes your problem?

**Comment by cw6365** [comment]
@gettalong thanks.. i'll test and let you know

**Comment by cw6365** [comment]
I still got the same actually..

```
GIT
  remote: https://github.com/gettalong/hexapdf.git
  revision: 1250a0603737ca2ae9845c6c1f4873bdd8287063
  branch: devel
  specs:
    hexapdf (0.47.0)
      cmdparse (~> 3.0, >= 3.0.3)
      geom2d (~> 0.4, >= 0.4.1)
      openssl (>= 2.2.1)
```

```
doc = HexaPDF::Document.open("#{Dir.pwd}/new-sample.pdf")

def signing_mechanism
  lambda do |io, byte_range|
    # Store the to-be-signed data in the local variable data
    io.pos = byte_range[0]
    data = io.read(byte_range[1])
    io.pos = byte_range[2]
    data << io.read(byte_range[3])
    "#{'0' * 20000}"
  end
end

options = {
  reason: 'Some reason',
  signature_type: :pades,
  signature_size: 20_000,
  external_signing: signing_mechanism, 
  doc_mdp_permissions: :form_filling 
}

@file.sign("signed.pdf", **options)

```

The file starts pdf 1.6 and ends pdf 1.6. The signing is performed with an external service which actually works well and produces the rosette author signature. The prob is when i re-open it to add another signature, it invalidates the first but i'm trying to with incremental: true, i thought this was default, so that might be my issue on that. 

Although its still not saving as a PDF 2.0 doc

### original 
<img width="1470" alt="Screenshot 2024-09-17 at 13 32 42" src="https://github.com/user-attachments/assets/d0d079cf-474d-475b-afcc-663c510dec6c">

### signed
<img width="1470" alt="Screenshot 2024-09-17 at 13 33 13" src="https://github.com/user-attachments/assets/4ab4d332-fd37-4341-b640-a11a551bf526">

**Comment by cw6365** [comment]
@gettalong right, ok cool. I'll test the multiple signers, thanks for your help.

**Comment by cw6365** [comment]
@gettalong the patch has fixed the multiple signing issue too, thanks again

**Comment by gettalong** [comment]
Great! And thanks for testing this out! I will release a new version with the changes in the coming days.

**Comment by cw6365** [comment]
@gettalong also with multiple signatures.. when i add an author signature which has one field, and form filling permissions.. i then fill out the field programatically with another signer.. this invalidates the author signature.. any ideas why?

```
    def add_dynamic_fields(fields)
      form = @file.acro_form(create: false)
      fields.each do |field|
        Hexagen::Render::RenderItem.build(
          field: field, pdf: @file, form: form
        ).complete
      end
    end

      def complete
        tx = @form.field_by_name(@item[:uuid])
        tx.field_value = @item[:field_value]
      end
```

<img width="1201" alt="Screenshot 2024-09-17 at 14 37 35" src="https://github.com/user-attachments/assets/c50bd1f6-593a-4f9c-b290-3b423a3332ac">

**Comment by gettalong** [comment]
@cw6365 Can you provide before and after PDFs?

If I interpret the image correctly, you are adding some text to the PDF (the "Adding some text to this sample")? This would invalidate the initial signature.

Another idea: Did you specify font and font size for the text field on creation? If not and no default values are set on the form level, HexaPDF will add the needed information which might also be considered an invalid change.

**Comment by cw6365** [comment]
These are the pdfs..

### Author signed pdf before 2nd signature
[signed-detatched.pdf](https://github.com/user-attachments/files/17032125/signed-detatched.pdf)

### 2nd signature with no form filling (author sig looks ok)
[pre-signed.pdf](https://github.com/user-attachments/files/17032135/pre-signed.pdf)

### 2nd signature with field filled out (invalidates author sig)
[pre-signed-with-field.pdf](https://github.com/user-attachments/files/17032153/pre-signed-with-field.pdf)

Ive had a look.. and apart from the /V flag with the value added the only difference i see between the pdfs with and without a value is an extra /Q flag.. i've looked at the pdf2 spec but can't see reference to a /Q flag.

I'll try with font sizes too, although i do specify the font size for the field when creating the pdf

<img width="550" alt="Screenshot 2024-09-17 at 17 40 17" src="https://github.com/user-attachments/assets/280c17d3-ddc1-41d8-9fe0-dc6f63240e8d">

**Comment by gettalong** [comment]
Okay, I'm a bit confused. The file `signed-detached.pdf` contains two revisions:

~~~
Document has 2 revisions
Revision 1
  Type      : xref table
  Objects   : 17
  Size      : 18
  Byte range: 0-5987
Revision 2
  Type      : xref table
  Objects   : 15
  Size      : 29
  Signed    : yes
  Byte range: 0-49847
~~~

And `pre-signed.pdf` contains three revisions:

~~~
Document has 3 revisions
Revision 1
  Type      : xref stream
  Objects   : 25
  Size      : 26
  Byte range: 0-458
Revision 2
  Type      : xref stream
  Objects   : 15
  Size      : 38
  Signed    : yes
  Byte range: 0-54794
Revision 3
  Type      : xref stream
  Objects   : 6
  Size      : 41
  Signed    : yes
  Byte range: 0-95915
~~~

One more signature, one more revision. So far so good! However, the revisions 1 and 2 of `pre-signed.pdf` don't match the revisions 1 and 2 of `signed-detached.pdf` which means that the file signed to get `pre-signed.pdf` is not `signed-detached.pdf`.

Regardless of that observation, I very much agree that the additional `/Q 0` might make Adobe Reader say that the signature is invalid. The thing is: 0 is the default value for `/Q`, so even if it is explicitly stated in the dictionary, there is no difference functionality-wise.

Could you try the latest version in the devel branch which should fix this? Note that the fix is only for fields which are initially created via HexaPDF but from what I see this is the case here.

**Comment by cw6365** [comment]
Thanks, i'll have a look in the morning as first test with rev 9ed078f didnt add the /Q flag by default to my text field. I'll clone locally instead of running from my Gemfile and debug

<img width="436" alt="Screenshot 2024-09-17 at 22 58 25" src="https://github.com/user-attachments/assets/bad37f2e-ed19-42f1-992a-7cfdfd39897b">

**Comment by cw6365** [comment]
@gettalong - the default :Q flag worked.. the gem was cached in my Docker first time.. the document is now validating with multiple signatures even after i fill the fields out. Thanks again for the help and the library.

<img width="1193" alt="Screenshot 2024-09-19 at 16 19 27" src="https://github.com/user-attachments/assets/a9c0084b-bce7-4a57-9e9c-4b31357703e7">

**Comment by gettalong** [comment]
@cw6365 Perfect, thank you for the feedback! I'm still waiting for confirmation on another change and after that I will cut a new release.
