### ISSUE TITLE
How to remove a section of text?

### ISSUE THREAD

**Issue by monkeysuffrage** [gettalong/hexapdf#37]
Is this possible? The description says PDF manipulation but I only see examples of adding things.

**Comment by gettalong** [comment]
Yes, you can remove a section of a text. However, determining in a page's content stream the instructions that describe the portion of the text that should be removed is not that easy in the general case.

You would need to write a subclass of [`HexaPDF::Content::Processor`](https://hexapdf.gettalong.org/api/HexaPDF/Content/Processor/index.html) (see [Show Character Bounding Box example](https://hexapdf.gettalong.org/examples/show_char_bboxes.html)) and filter out the necessary parts.

To do this you have first to think about how to describe the section of the text? By its content? By its location on the page? By its text color? The easiest one of those is by text color, then location on the page and the by content (because text in a PDF may be written in any order).

There is currently nothing pre-built in HexaPDF for this situation.

**Comment by monkeysuffrage** [comment]
OK so in that example boxes is a bounding box, is there a method to delete
that somewhere? I tried inspecting different objects and grepping for a
delete method but I didn't find anything.

**Comment by gettalong** [comment]
As I said you would need to filter out the necessary parts. Ie. you need to process the content stream, write the things you need to a temporary string, leave out the things you don't need, and then overwrite the content stream with the temporary string. You can see an example at https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/task/optimize.rb#L205 but note that this doesn't do the filtering part.

So first determine by which means (content, location, property) you want to filter out the text. Only then can you choose the right tools to proceed.

**Comment by monkeysuffrage** [comment]
Ok, let's say location. How would I filter out text based on location?

**Comment by gettalong** [comment]
Then you can use the bounding box of each character to determine whether it lies inside your determined area or outside.

I would

* Subclass `HexaPDF::Content::Processor` like in the Show Character Bounding Box example.
* Override the `#process(operator, operands)` method like in the optimize task but call `#super` so that the necessary graphics state manipulation is done.
* Directly write out any operators that aren't of concern to the temporary string.
* Use `#decode_text_with_positioning` for the `show_text_with_positioning` and `show_text` operators to get the bounding boxes.
* If the bounding box of the `CompositeBox` is inside/outside the area, completely drop or use the operator (i.e. write it out to the temporary string as is).
* Otherwise you need to check the bounding boxes for each glyph and and remove those that are inside the area. Note that this is not as easy to do because a glyph may be represented by one or more bytes in case of composite fonts. In such a case you would need to do some custom parsing similar to https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/font/cmap.rb#L133.

**Comment by monkeysuffrage** [comment]
Hmm, this sounds pretty complicated just to delete some text. Right now
covering the text with white rectangles and I guess that's going to have to
do.

**Comment by gettalong** [comment]
Yep, semantic information extraction or modification of a page's content is one of the harder things to do for PDF files. There is a reason such things are not widespread...

Please note that if you cover text with white rectangles that the text will still be selectable within PDF reader applications! So you are just hiding the text but if someone inadvertently selects some of the visible text, the invisible one may be selected, too.

**Comment by gettalong** [comment]
@monkeysuffrage I will close this issue since there isn't anything more to add currently. If there is still a problem, please comment.

**Comment by monkeysuffrage** [comment]
I never got this working actually. A working example of removing text would
be very useful.

**Comment by gettalong** [comment]
As I said, it is a pretty complex task. What I want to do is to provide a processor that turns the text of a page into an object that can be queried for strings and allows for some modifications. This is already on my TODO list.

**Comment by joshco** [comment]
@monkeysuffrage I have a workaround.

I found a work around the issue of the text still being present underneath the overlay canvass where redaction happens as @gettalong says:
> Please note that if you cover text with white rectangles that the text will still be selectable within PDF reader applications!

I use RMagick, (and ghostscript) to write the output as a PDF with graphics instead of text.on the pages.  So there's no longer a layer of text.  The PDFs obviously get bigger, but until I find a way to actually remove the unwanted text objects, this is working for me.  

Whether that works for youy depends on what your goal is.

Mine is to redact personal information like email addresses and phone numbers, in a way that cannot be recovered by someone who had the redacted document.

I started with this code in issue #31 

https://github.com/gettalong/hexapdf/issues/31#issuecomment-395745621

rather than let HexaPDF write the output to a file, i write it to a StringIO object.  That's a Ruby object which is an in-memory buffer, but has the same methods and interface as a file object.  

Then I read from the StringIO into RMagick's ImageList, using its from_blob() method.  I didn't want to deal with writing temporary files to disk, especially in docker/heroku which is slow and inefficient..

The ImageList will bring the PDF pages in the stream as images in the ImageList. Then you can call the write method on on the ImageList to write it to the PDF as embedded images.  There are options for graphics quality.

The code in the above referenced example is quite clever since it uses positional information to keep the text objects together which may have 1 char, or be out of order in the file.

The cherry on top for me, is that instead of searching just for known strings, I use a regular expression that matches emails and phone numbers.  

Now I feed my app PDFs, and it automatically churns out redacted PDFs with no emails or phone numbers.  It has saved me SOOO much time.

Getting ImageMagick (what powers RMagick) and ghostscript has always been a frightening experience, especially if you are running on windows.

nowadays, I use docker and or WSL, so it's easier.  I figured out the right gems to include that can work with Heroku Buildpacks, or with some additions to a Dockerfile

LMK if you want to know more.

**Comment by sixtyfive** [comment]
Hi @gettalong,

slowly getting the hang of it now and trying to follow along the solution you suggested above for @monkeysuffrage's problem:

> I would
>     * […]
>     * Override the `#process(operator, operands)` method like in the optimize task but call `#super` […]
>     * […]
>     * […]

unfortunately, when trying to call `#super`, this happens:

```ruby
hexapdf/content/operator.rb:322:in `invoke': undefined method `ext_gstate' for nil:NilClass (NoMethodError)
```

I put a M(n)WE at https://gist.github.com/sixtyfive/d3a1994613f4de2bbf9a114ab34f9052. What am I doing wrong?

**Comment by gettalong** [comment]
@sixtyfive See my comments on the gist, they should answer all your questions.

**Comment by sixtyfive** [comment]
Thank you @gettalong, that helped immensely and I can now remove any text I like. Will leave the Gist up for others' reference.

**Comment by gettalong** [comment]
@sixtyfive Glad to hear that! Just one thing: To remove *"any text you like"*, your also need to arrange the text/characters according to their position. There is something like a line structure in PDF but if the PDF producer arranged words in another way you will not get the correct result.

**Comment by sixtyfive** [comment]
Yes, I noticed, it's quite haphazard sometimes. For what I wanted to do, it was fine as the positions of everything need to stay the same. What I did try and failed to accomplish was to manipulate the position of an existing ContentBox inside of `CustomProcessor#process`. What's the deal with some things being `ShowText`and some others `ShowTextWithPositioning` but the former also having positions after you apply `#decode_text_with_positioning` to them (so now you have those positions and can merrily play with them, but how do you serialize it back into the content stream)?

**Comment by gettalong** [comment]
The `ShowText` and `ShowTextWithPositioning` operator implementations are just two of the available text showing operators of PDF. Another one would be `MoveTextNextLineAndShowText`. And since the PDF reader needs to know where to put the text, all carry position information.

What makes `ShowTextWithPositioning` special is that there can be additional spacings (e.g. kerning) between the characters. All others just place one character after the other. If you want to dive deeper, have a look at section 9.4 of the PDF specification.

As for changing the contents: The content processor is solely for reading a content stream. If you need to modify some operators, you need to change the operators and/or their arguments. E.g. when you want to modify positions. In your gist you just serialize the operators again (or probably leave them out for redacted parts). So you would need to change the operators/operands before serialization and/or insert other operators.

**Comment by SyedJawadNisar** [comment]
After thoroughly examining the preceding conversation, I found valuable insights to assist me in my task. However, as I attempted to extract or replace text from the PDF using the coordinates of a canvas box, I encountered two main challenges:

1. Determining the width of my text poses a difficulty since I can only retrieve its starting point.
2. When I successfully replace or remove a portion of text, it disrupts the page layout, creating a messy appearance. I assume I need to update the numerical values after replacing the text, but how can I determine the appropriate values?

Furthermore, if anyone is aware of a more effective solution than the provided gem, I am open to suggestions. The link of code describing my question can be found here: 
https://gist.github.com/SyedJawadNisar/34f4adfb249d66ef2bc7b4f8e228cb1a
Please! review this and guide me.

**Comment by gettalong** [comment]
@SyedJawadNisar Here are some pointers:

ad 1) The width of the text can be determined by using the helper method `#decode_text_with_positioning`. See https://hexapdf.gettalong.org/examples/show_char_bboxes.html for an example on how to use it.

ad 2) This is to be expected because a PDF file is _not_ a like a text document. In a text document, be it a plain text document or something like OpenDocument Text, the viewing/editing program does all the text position calculations. However, with PDF the PDF creation application does those calculations and puts the coordinates of each glyph into the PDF. So if you just replace characters like you do or remove them, the layout will (most certainly) be wrong.

If you just want to remove some text, it might be easier because the rest of the text can stay in the same position. For this you would need to determine the width of the to-be-removed text (see my comment above) and then replace it with a text position adjustment value (and maybe change the operator to the one supporting such values).

**Comment by joshco** [comment]
In my code I replace the text underneath the redaction with 'x' chars.  That keeps the formatting roughly, but not perfectly aligned

**Comment by SyedJawadNisar** [comment]
Hi @gettalong,
There should be a solution to address the positioning issue that arises after text replacement. How can I adjust the (text position adjustment value)? Could you provide more guidance on this?

Additionally, I have another question concerning redaction.

If I overlay canvas2 on canvas1, what impact does it have on canvas1? Will it stay accessible if someone decodes our PDF and tries to retrieve canvas1?
I assume canvas1 remains accessible. Can you offer guidance on a technique to remove or replace underlying images or canvases within the PDF?

**Comment by gettalong** [comment]
@SyedJawadNisar PDF text editing is *not* a trivial issue and there is *no easy* solution for positioning issues after text replacement because for this one would need to understand the complete layout of the text (i.e. where are line breaks, is the text in columns, should text flow around images...). This is not something that will be handled by HexaPDF in the near future.

As for your canvas question: Once you write the PDF, there is only a single content stream associated with the page that represents what was initially on the page and what you have added (to be exact, that single content stream will consist of multiple PDF stream objects but that's an implementation detail). So everything that was already there will still be there. To remove something from the initial content stream, you would need to process it to filter out what you don't want to have there. In case of images, it is rather easy because they are stored as separate objects. So you would just need to replace the image object with the replacement image object.  Have a look at section 7.8 of the PDF specification for a deeper understanding of this. The images used in a page are accessible via `page.resources[:XObject]`.

**Comment by SyedJawadNisar** [comment]
@gettalong, In your earlier comment, you suggested that "If you just want to remove some text, it might be easier because the rest of the text can stay in the same position. For this you would need to determine the width of the to-be-removed text (see my comment above) and then replace it with a text position adjustment value (and maybe change the operator to the one supporting such values)."

Could you provide further details on this? How can I proceed with this approach if I need to remove specific text? Let's assume I already have the text to be removed and its position.

**Comment by gettalong** [comment]
@SyedJawadNisar The premise of my comment is correct. Alas, the practical implementation is another matter :frowning_face: 

To provide a starting point for further exploration I wanted to write a simple content processor for removing characters. The straight-forward idea I had in mind does what it should but not working on this part of HexaPDF/the PDF spec for around 6 years let me forget some details.

There is a problem supporting multi-byte encoded fonts (like what  HexaPDF uses for TrueType font support). The problem  lies in the fact that a character code, for example 15, can be encoded as a single byte 0x0F or two bytes 0x000F (or three or four). That information is currently lost when decoding the content stream. So turning a decoded stream back to its encoded form is currently missing (this is also the reason why you usually can't use an embedded font to create new text).

I will have a look at what needs to be changed to provide all the information for decoding and re-encoding text in a content processor. Sorry for that!
