### ISSUE TITLE
How to flatten annotations?

### ISSUE THREAD

**Issue by CodeMonkeySteve** [gettalong/hexapdf#38]
I'm looking for help with converting an AcroForm PDF to a read-only PDF by "flattening" the annotations (specifically, the form fields).  I can get the result I want using print-to-PDF in various PDF reader apps.  By any chance does HexaPDF have any support for such an operation, or will I need to process the PDF file myself?  

If I must do the processing myself, can you offer any advice?  Is it just a matter of converting Annotation objects into equivalent text/graphic objects with the same bounding box, font, etc.?  That should be straight-forward for text, but I'm not sure how to handle, e.g., the Appearance dictionary for checkboxes.  

Any assistance would be greatly appreciated, thanks ...

**Comment by gettalong** [comment]
I haven't dug too deep into the whole AcroForm business yet. However, as far as I understand it AcroForm provides two representations of the value of each form field:

* The value itself as part of the field object. For example, for a checkbox whether it is checked or not.
* The appearance of the field object, as part of the widget annotation on a page. Taking the example of the checkbox, there would be two "appearance streams", ie. content streams, that defined the appearance of the checked and unchecked checkbox. For a text field, there would be an appearance stream of the rendered text.

So if you have a checkbox which is checked, you would need to take the appearance stream for the checked version and overlay it at the correct position (i.e. the `/Rect` entry in the corresponding widget annotation). Since the appearance streams are form XObjects you can use the `Canvas#xobject` to easily paint them on the canvas.

Note that there is a possibility that some fields are constructed interactively, e.g. via Javascript, when viewing the PDF in a reader application. This means that those fields would be much harder to correctly flatten if there is not yet an appropriate appearance stream.

After you have used all fields' appearance streams, you need to remove the AcroForm objects which prevents re-editing the PDF.

I recommend reading section 12.7 "Interactive Forms" (leave out anything that has to do with XFA - if you need that it probably gets much more complicated) of the PDF 1.7 specification (freely available at Adobe's website) or, if you have access to, the equivalent section in the PDF 2.0 specification which should be much more detailed and better to follow (only heard that this should be the case).

Another thing to try: Fill out the PDF with a reader application and use `hexapdf inspect` (or view the PDF in an editor) to see what the reader application changed. I have done that with okular on Linux and it creates a new revision with all the changes to the PDF form. So it's rather easy to see the changes.

Finally, if you want to fill out the PDF with HexaPDF and generate the correct appearance streams, it might be much harder.

Does this help?

**Comment by CodeMonkeySteve** [comment]
Thanks for all the info, that's really helpful.  I'm currently using HexaPDF to parse the PDF structure and read/write Form field values (including adding an Ink annotation for hand-drawn signatures).  I think I can work out how to layout the text from a Text field, and how to apply the Appearance Stream for checkboxes (thanks!).  I'll have some control over the PDFs used, so I shouldn't need to worry about supporting Javascript, I just need to replace the Annotations with graphic objects.  The only questions I have at this point are:

* What's the best way to remove an Annotation object (i.e. while iterating over the document, if possible)?
* How do I draw text using the font from the Annotation's Resource Dictionary?

Thanks for all your help.

**Comment by CodeMonkeySteve** [comment]
Well, I answered my first question: `document.delete(obj)` (that was easy)
And I have checkbox rendering working: `canvas.xobject( document.object(obj[:AP][:N][obj[:V]]), at: [obj[:Rect][0], obj[:Rect][1]] )`
The only open question is how to use an existing object's font in the canvas.

**Comment by gettalong** [comment]
Generally, there is currently no built-in way to re-use fonts from a PDF in HexaPDF.

However, most of the time the fonts used in form fields are the ones built into the PDF format, or, more correctly, the ones every reader has to understand. These fonts are called the *Standard 14 PDF fonts*. So if one of those are used, there is no problem since you can just determine which one of the standard fonts it is and use it.

However, if the field's font references an embedded font and this font is *not* fully embedded but subset there may be a problem since the parts needed to convert from characters to glyph may be missing (e.g. when HexaPDF embeds a TTF font this conversion map is stripped out to save space because it is not needed anymore).

Also not that you need to take the `/DA` and `/AP` keys into account that specify the appearance of the text. And the resources specified on the main `/AcroForm` object.

So if you have some control over the PDFs you should try to restrict the fonts used in form fields to one of the standard 14 fonts.

**Comment by CodeMonkeySteve** [comment]
I'd forgotten that PDF may only include the glyphs it actually uses, not the whole font.  And I'm not sure there's any reason to keep the fonts the same, anyway.  Set it to Helvetica, works great.

Thanks for all your help.

**Comment by gettalong** [comment]
@CodeMonkeySteve Just an FYI: The next version of HexaPDF to be released today will have direct support for flattening annotations and also takes care that the annotations are properly places and scaled.
