### ISSUE TITLE
Getting error while processing document with HexaPDF::Content::Processor

### ISSUE THREAD

**Issue by priyanshujain** [gettalong/hexapdf#39]
```ruby
doc = HexaPDF::Document.open(file_name)
puts "Blacken strings [#{strings_to_black}], inside [#{file_name}]."
doc.pages.each.with_index do |page, index|
  processor = ShowTextProcessor.new(page, strings_to_black)
  page.process_contents(processor)
end
```
/home/priyanshu/.rvm/gems/ruby-2.4.1/gems/hexapdf-0.6.0/lib/hexapdf/content/color_space.rb:183:in 
`new': wrong number of arguments (given 1, expected 0) (ArgumentError)
	from /home/priyanshu/.rvm/gems/ruby-2.4.1/gems/hexapdf-0.6.0/lib/hexapdf/type/resources.rb:82:in `color_space'
	from /home/priyanshu/.rvm/gems/ruby-2.4.1/gems/hexapdf-0.6.0/lib/hexapdf/content/operator.rb:381:in `invoke'
	from /home/priyanshu/.rvm/gems/ruby-2.4.1/gems/hexapdf-0.6.0/lib/hexapdf/content/processor.rb:359:in `process'
	from /home/priyanshu/.rvm/gems/ruby-2.4.1/gems/hexapdf-0.6.0/lib/hexapdf/content/parser.rb:166:in `parse'
	from /home/priyanshu/.rvm/gems/ruby-2.4.1/gems/hexapdf-0.6.0/lib/hexapdf/content/parser.rb:154:in `parse'
	from /home/priyanshu/.rvm/gems/ruby-2.4.1/gems/hexapdf-0.6.0/lib/hexapdf/type/page.rb:262:in `process_contents'
	from blackout.rb:35:in `block in <main>'
	from /home/priyanshu/.rvm/gems/ruby-2.4.1/gems/hexapdf-0.6.0/lib/hexapdf/type/page_tree_node.rb:206:in `block in each_page'
	from /home/priyanshu/.rvm/gems/ruby-2.4.1/gems/hexapdf-0.6.0/lib/hexapdf/type/page_tree_node.rb:203:in `each'
	from /home/priyanshu/.rvm/gems/ruby-2.4.1/gems/hexapdf-0.6.0/lib/hexapdf/type/page_tree_node.rb:203:in `each_page'
	from blackout.rb:33:in `with_index'
	from blackout.rb:33:in `<main>'
```

**Comment by gettalong** [comment]
Please provide a small runnable example so that I can reproduce the problem - thanks!

**Comment by priyanshujain** [comment]
Document is [document.pdf](https://github.com/gettalong/hexapdf/files/2091199/document.pdf)

and code is `https://github.com/gettalong/hexapdf/issues/31#issuecomment-395745621`

**Comment by gettalong** [comment]
Thanks for the example document - this seems to be a problem with the resolution of indirect standard color spaces. Will fix this for the next release.

**Comment by gettalong** [comment]
@priyanshujain Fixed and new release is out!

**Comment by priyanshujain** [comment]
@gettalong  Thanks, have you pushed it to gems.

**Comment by priyanshujain** [comment]
@gettalong  Got it Thank you very much. I think I should start contribute to hexapdf, can you give me some small task to start with?

**Comment by gettalong** [comment]
I have a TODO list but most of those items require in-depth understanding of how HexaPDF works and knowledge of the PDF specification. You could look at the [implementation status](https://github.com/gettalong/hexapdf/wiki/PDF-1.7-Implementation-Status) to see what's missing from the PDF spec - for example, most of section "12 Interactive Features" and pick something (for example, add more annotation or action implementations). Before you start work please open a ticket so that we can discuss the feature etc.

Please note that you need need to sign the contributor license agreement (more info at http://hexapdf.gettalong.org/contributing.html) before I can accept contributions.
