### ISSUE TITLE
Is it possible to change the PDF version of a file?

### ISSUE THREAD

**Issue by davidalejandroaguilar** [gettalong/hexapdf#41]
I've read through the documentation but haven't found a way to do so, so as a last resort, I'm asking here.

**Comment by gettalong** [comment]
Yes, it is, see https://hexapdf.gettalong.org/api/HexaPDF/Document/index.html#method-i-version-3D.

The minimum version is 1.2 (set here https://github.com/gettalong/hexapdf/blob/master/lib/hexapdf/document.rb#L129). When the document gets validated on writing and features of later versions are used, the version is automatically adjusted to the lowest version needed for the features to work. For example, if object streams are used, the PDF version needs to be at least 1.5.

Please note that this automatic version determination is not 100% fool-proof because only the parts of the PDF specification that are implemented and have validation attached will update the version. However, it should still work well in many cases for now and will get better in the future.

**Comment by davidalejandroaguilar** [comment]
Great! It worked! Thanks a lot.
