### ISSUE TITLE
JRuby Support

### ISSUE THREAD

**Issue by jalevin** [gettalong/hexapdf#47]
Does HexaPDF currently support any versions of JRuby?

**Comment by gettalong** [comment]
I have just installed JRuby 9.2.0.0 (`jruby 9.2.0.0 (2.5.0) 2018-05-24 81156a8 Java HotSpot(TM) 64-Bit Server VM 25.111-b14 on 1.8.0_111-b14 +jit [linux-x86_64]`) and it mostly works (only . However, since the refinement implementation of JRuby still has some bugs, the text layouting functionality won't  work. Once those bugs are gone (the JRuby team is currently trying to improve the refinement support) it should completely work with JRuby.

Another thing is that JRuby is, in this case, a bit slower than MRI. The test suite takes 17seconds (going up to 31seconds with startup), compared to 2.1seconds/4.8seconds. This is rather extreme since the test suite test most execution paths only once but I don't know if JRuby works better once it is warmed up.

**Comment by gettalong** [comment]
I will close this issue - if you still have question, feel free to add comments!
