### ISSUE TITLE
Potential undocumented change

### ISSUE THREAD

**Issue by dwightwatson** [gettalong/hexapdf#50]
Hi there, thanks for this package - it's a blessing.

Just noticed a breakage during the update from `0.7.0` to `0.8.0`.

```rb
Failure/Error:
box = HexaPDF::Layout::TextLayouter.create(sanitize(content),
                                             width: max_width,
                                             font: canvas.font,
                                             fill_color: canvas.fill_color)
      
NoMethodError: undefined method `create' for HexaPDF::Layout::TextLayouter:Class
```

It looks as though in bff346aa1ed2c011778f360dfa7edabf4ba5ec82 `HexaPDF::Layout::TextLayouter.create` was removed and internal uses were changed to `HexaPDF::Layout::TextFragment.create`. I'm not sure if this is a drop-in replacement for the former method or not, but there is no mention of that method specifically in the CHANGELOG.

**Comment by gettalong** [comment]
Thanks! And sorry, I should have mentioned it clearer in the changelog entry description for the commit you mention that the TextLayouter class itself was changed, i.e. it was refactored.

The `TextLayouter.create` method was removed because it didn't make sense anymore:

* When a TextLayouter instance gets created now, you just need to supply its style that defines, for example, how line breaking and layouting is done. Nothing else is happening here.
* Later you call `#fit(items, width, height)` to do the actual layouting of items. No state is stored in the TextLayouter itself anymore since the result gets returned as a separate object.

This means that `TextFragment.create` is not a drop-in replacement but that you have to change your code: You should use `TextFragment.create` with `font` and `fill_color`, then wrap the resulting fragment in array so that it is acceptable as the `items` argument for `TextLayouter#fit`. Then create a TextLayouter, probably with the style from the created text fragment, and call `#fit` supplying the items, `max_width` as width and a height (use a large enough number if necessary).

See the change to the line wrapping benchmark script as an example: https://github.com/gettalong/hexapdf/commit/bff346aa1ed2c011778f360dfa7edabf4ba5ec82#diff-377343b8a3cbc59ae727db9530fd3536

I don't think that future versions need so drastic changes in the layout part of HexaPDF. For the next release I intend to implement a high-level class that wraps all this stuff to make it straight-forward to use. Until now this was all just plumbing and preparing.

If you need more information, let me know!

**Comment by dwightwatson** [comment]
Ah awesome - thanks for taking the time to explain the change. It's a lot clearer now, thank you!
