### ISSUE TITLE
Rotating pages

### ISSUE THREAD

**Issue by bovender** [gettalong/hexapdf#65]
Hi,

I need to rotate some pages in a given PDF document. The `modify` command advertises this capability, but the help text seems to be lacking any instructions? Or is it just me not seeing it?

**Comment by gettalong** [comment]
Please have a look at the [manual page](https://hexapdf.gettalong.org/documentation/hexapdf.1.html#pages-specification) of the `hexapdf`` command. There you will find detailed information. The built-in help text is just a reminder of the available commands/options with short descriptions.

**Comment by bovender** [comment]
Thanks very much. To my defense, I did issue `man hexapdf` before I posted this, but the man page is not installed on my system. I have `rbenv` installed, maybe that's the problem? In any case, thanks again, I'll read the man page online in the future...

**Comment by gettalong** [comment]
No problem! FYI: If you install HexaPDF via Rubygems and also have the `manpages` gem installed, a `man hexapdf` will work. I guess this should also work when rbenv is used.

**Comment by rubyFeedback** [comment]
I just came across this here after a google search. So far in my pdf-wrapper I have this variant with qpdf:

    qpdf --rotate=90 --replace-input foobar.pdf

The linked in document (see the URL https://hexapdf.gettalong.org/documentation/hexapdf.1.html#pages-specification) has "EXAMPLES" but nothing follows right now; not sure if this is on purpose or by accident. It may be useful to add a corresponding full, commandline example via hexapdf, similar to qpdf. I will probably figure it out after reading the documentation (e. g. the "1-e: All pages of the document." part combined via "r"), but a copy/pasteable example may IMO be better. (Also I think --rotate= may be a useful alias, simply as mnemonic, but that's a subjective statement of course as people may disagree on what is useful and what is not.)

Edit: Nope, I was unable to get it to work. For comparison, qpdf presently provides a nice overview here with some specific examples:

https://qpdf.readthedocs.io/en/stable/cli.html

See these parts specifically:

    Examples:

    qpdf in.pdf out.pdf --rotate=+90:2,4,6 --rotate=+180:7-8: rotate pages 2, 4, and 6 by 90 degrees clockwise from their original rotation

    qpdf in.pdf out.pdf --rotate=+180: rotate all pages by 180 degrees

    qpdf in.pdf out.pdf --rotate=0: force each page to be displayed in its natural orientation, which would undo the effect of any rotations previously applied in page metadata.

By the way, one slightly confusing thing is this here, when I issue:

    hexapdf modify

I get this result:

    Error while parsing command line:
        Not enough arguments provided, minimum is: 2 - IN_FILE OUT_FILE

I understand that this is the technically correct information, e. g. showing
that the user should give two arguments, input-pdf and output-pdf, but
the part that is confusing is that this may be incomplete in what the user
may have wanted to do. So, in this context, the user (me) wanted to rotate,
via "hexapdf modify". I understand that hexapdf can not infer this, because
modify may have different subcommands (may be easier to add "rotate"
though), but the message does not really help solve the issue specifically.
Because I now know that I need to provide two arguments, e. g. inputfile
and output file, but I still don't know the correct syntax to rotate the .pdf
file. Would it be possible to add at the least one example that can be 
copy/pasted, similar to how qpdf handles this? Google search has unfortunately
become really useless in the last years so I think the better the intrinsic 
quality of projects, the less we may depend on google search results.

**Comment by gettalong** [comment]
@rubyFeedback I think I see what you mean. Some things like `hexapdf modify` outputting a terse error message are probably not gonna change. However, moving the individual examples from the general EXAMPLE section to the individual command sections is probably a good idea. I will sleep on it and the decide.

And I can certainly add a few more example invocations for common usage scenarios.

**Comment by gettalong** [comment]
@rubyFeedback I have moved the examples to the individual command sections and also added some new examples. This change will be visible with the next release.
