### ISSUE TITLE
Unable to copy rendered text. How to embed font correctly?

### ISSUE THREAD

**Issue by iSunRise** [gettalong/hexapdf#72]
Hi Thomas,

Thanks you again for your great project.

Could you help me with custom font embedding? I use a custom font and load it from a file like
```
default_font = HexaPDF::FontLoader::FromFile.call(@pdf_document, FONT_FILE_PATH)
```
then I render text using text fragment
```
text_fragment = HexaPDF::Layout::TextFragment.create("some text", font: default_font)
text_fragment.draw(canvas, x, y)
```
It renders pdf as expected, but when I copy/paste rendered text I'm getting weird symbols like
```
����� ���� 
```

I guess I should embed font into pdf somehow, my font is 140kb but pdf are lighter. However, I'd like to keep pdf files as light as possible.. I've attached a pdf with example of problem and the font itself.

Please advice,
Thanks

[copy-issue.pdf](https://github.com/gettalong/hexapdf/files/3275105/copy-issue.pdf)
[LiberationSans-BoldItalic.ttf.zip](https://github.com/gettalong/hexapdf/files/3275110/LiberationSans-BoldItalic.ttf.zip)

**Comment by gettalong** [comment]
The TrueType font file you attached seems to have an invalid mapping table and therefore HexaPDF substitutes the 0xFFFD character because it can't find the Unicode code for some glyphs. I have tried with a newer version and there everything works as expected.

I suggest using an updated version of these fonts, you can get them at https://github.com/liberationfonts/liberation-fonts/releases

**Comment by iSunRise** [comment]
@gettalong, you're right, thanks!
