### ISSUE TITLE
Fixing invalid PDFs missing URIs

### ISSUE THREAD

**Issue by genericsteele** [gettalong/hexapdf#76]
Often, we get a PDF from a customer that was partially filled out using another application. Just about as often, that other application doesn't do a great job with creating a valid PDF that can be modified and optimized. The most common error we deal with is `HexaPDF::Error: Validation error for (51,0): Required field URI is not set`.

In order to fix those documents, I just download the source file, export it as a PDF (using macOs' Preview), and re-upload it. That fixes the validation 100% of the time.

Is there a way HexaPDF could auto-fix certain types of validation errors when optimizing?

**Comment by gettalong** [comment]
As you wrote, this will most probably be a problem with the source PDF. However, to make sure HexaPDF reports this correctly, could you provide a PDF that shows this error?

As for auto-fixing: Validation errors that can be automatically fixed, are automatically fixed with the default configuration. However, if the URI is indeed missing, there is no useful default value to fill in.

There is currently no way in the validation logic to provide custom corrections on errors, it is only possible to get notified on validation problems. I will think about how to provide something like this. Then you could handle this validation problem in any way you see fit - sounds good?

**Comment by genericsteele** [comment]
Thanks for helping out with this! Because you couldn't see the issue with the original file, I found a few issues with our workflow & a conversion API we use that are causing the problem.

I'm closing this!
