### ISSUE TITLE
Give font hints and/or a possibility for having a look at available fonts

### ISSUE THREAD

**Issue by alexanderadam** [gettalong/hexapdf#83]
It would be nice to have

```
HexaPDF::Error:
  The requested font 'Somename' in variant 'Somevariant' couldn't be found. Did you mean one of these: Times, Foo.ttf, Bar Baz?
```

instead of

```
HexaPDF::Error:
  The requested font 'Somename' in variant 'Somevariant' couldn't be found
```

And maybe a method `#available_font_names` that could be used to inspect the available fonts and variants.

**Comment by gettalong** [comment]
I will have a look at it but I think that both are doable for the next release.

**Comment by alexanderadam** [comment]
Awesome!

Did you read about the [`Gemfile`/`gemspec`/`geom2d` issue in the PS of the other issue](https://github.com/gettalong/hexapdf/issues/82)?

**Comment by gettalong** [comment]
Thanks for this enhancement idea - I have implemented it!

**Comment by alexanderadam** [comment]
Thank you, I can just repeat myself: you are awesome!
Really. Not just because of this particular issue but also because the PDF specification appears to me like rocket science. :wink:

**Comment by gettalong** [comment]
Thanks!

PDF is not really rocket science but being developed so long by one company that did things which they don't really specified, there are some hazy parts which are hard. That got much better since PDF becoming an ISO standard and version 2.0.

Apart from that you just have to read the 700+ pages of the specification twice or thrice and all the other referenced specs (PNG, TIFF, AES, TTF, OTF, Type1 fonts, CFF fonts, Unicode normalization, XMP, ...) and you are good to go :wink:
