### ISSUE TITLE
Scaling text size to fit a box.

### ISSUE THREAD

**Issue by brandon-zeeb-nw** [gettalong/hexapdf#84]
I'm looking through the documentation and I don't immediately see a way of scaling a TextFragment to a box, or more specifically, reducing the font size until all text fits within the box bounds.  How would you recommend we approach this problem with Hexapdf?

**Comment by gettalong** [comment]
There is nothing built-in to do this. However, you can use the `HexaPDF::Layout::TextLayouter` class to calculate the result of layouting the text. If the result is a success, draw it, otherwise reduce the font size. Something like this:

~~~ ruby
require 'hexapdf'

doc = HexaPDF::Document.new
sample_text = "Lorem ipsum dolor sit amet, con\u{00AD}sectetur
adipis\u{00AD}cing elit, sed do eiusmod tempor incididunt ut labore et
dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation
ullamco laboris nisi ut aliquip ex ea commodo consequat. ".tr("\n", " ")

style = HexaPDF::Layout::Style.new(font: doc.fonts.add('Times'), font_size: 10)
fragments = [HexaPDF::Layout::TextFragment.create(sample_text, style)]
tl = HexaPDF::Layout::TextLayouter.new(style)
while true
  result = tl.fit(fragments, 30, 10)
  break if result.status == :success
  style.font_size *= 0.95
  style.clear_cache
end
canvas = doc.pages.add.canvas
result.draw(canvas, 20, 100)

doc.write("box.pdf")
~~~

You could also try using a binary search for the best font size instead of just making the font size smaller and smaller.

Does this help?

Similarly, if you want to fit text into a bigger box, just reverse the condition.

**Comment by brandon-zeeb-nw** [comment]
This is very helpful!  Thanks for the code example

**Comment by gettalong** [comment]
One more thing: The result of `#fit` can be `:success`, `:height` (i.e. there wasn't enough height to lay out all items) or `:box_too_wide`. The last one is given if a single item is larger than the box (think eg. fixed size inline image). So you probably need to take that possibility into account in your code.
