### ISSUE TITLE
Alignment of fields with same name across documents not always respected after documents are combined

### ISSUE THREAD

**Issue by smiller** [gettalong/hexapdf#89]
I'm pretty sure this is a “different implementations of the pdf spec are screwy” rather than a  HexaPDF issue, but I hoped you might recognize it / have an idea of how to tackle it / whether it can be tackled.

Given two pdf forms with the a field with the same name, say `address`, but in one the field is right-aligned and in the other it's left-aligned.

When you combine the forms, starting with the left-aligned one, in the combined pdf, the first page has the left-aligned form and the second page has the right-aligned one.

And when you combine the forms, starting with the right-aligned one, in the combined pdf in Preview for Mac, you see the same, the right-aligned form followed by the left-aligned form.

**But** in Chrome or Acrobat, both fields are right-aligned.  It appears to ignore field alignment data from documents after the first one, provided a right-aligned one is before left-aligned ones.  (It does respect field alignment if the left-aligned one is before right-aligned ones.  Apparently.)

Repo with `fill_in_form.rb` script and all the starting and resulting files at: https://github.com/smiller/pdf-form-test-alignment

As I say, this feels clearly like a weird edge case of pdf spec implementation rather than anything to do with HexaPDF, but if it looks familiar or rings a bell or you see a clever way around it that is eluding me, I'd be very grateful.

**Comment by gettalong** [comment]
I will see if I find something but as you said it may just be viewer-dependent.

Have you tried merging the filled in files with another application that supports form merging? I ask because [this line](https://github.com/smiller/pdf-form-test-alignment/blob/master/fill_in_form.rb#L48) just fills in one key of the main acroform dictionary. It may be possible that for this to work correctly the main acroform dictionary must be a correct one.

One additional note: This line https://github.com/smiller/pdf-form-test-alignment/blob/master/fill_in_form.rb#L5 won't be necessary starting with the next release since arrays are now mapped to a special wrapper class like it is already with hashes and Dictionary. So if there is a field definition as is the case with the `/Annots` key of a page, references will automatically be resolved.

**Comment by gettalong** [comment]
I have tried various things and it seems that the problem is what is meant in the spec by `/Q` having a default value. In the spec it says that the default value of `/Q` is 0, meaning left-justified. For me that implies that whenever the `/Q` entry is missing, the viewer has to assume that it actually has the value 0.

However, Acrobat and Chrome seem to say in case of right-then-left: There is no `/Q` value for this field *but* there is another field with the same name on the previous page that has `/Q 2`, so we just use this. In case of left-then-right, the first field the viewer comes across has no `/Q`, so uses the default value.

When explicitly setting `/Q 0` for the PDF with left-aligned field, Acrobat and Chrome show them correctly. Just change [line 15](https://github.com/smiller/pdf-form-test-alignment/blob/master/fill_in_form.rb#L15) to `field[:Q] = 0` and it will work.

I will have to remember this once I implement field types because the optimization task automatically removes dictionary keys that have their default value set. Maybe this optimization shouldn't be run by default to avoid such problems...

Does this solution work for you?

**Comment by smiller** [comment]
This absolutely works in the test case, thank you very much for your help.  Now trying to see if `field[:Q] ||= 0` will work in the real code, where we're reading bunches of fields from longer pdf forms and we don't know within the code whether they should be right- or left-aligned.  Will report back.

**Comment by smiller** [comment]
First couple of cases I looked at this appears to do the trick.  I shall look at some more, as I had a long list of problem cases, but coming back to say again thank you very much indeed for your help with this.

**Comment by smiller** [comment]
Tried some more, and yes, it looks like `field[:Q] ||= 0` completely solves our problem and I'm happy for this issue to be closed accordingly.  Thanks very much again!

**Comment by smiller** [comment]
Actually, one more question, if I could, as I think we're having exactly the same problem with multiline form fields, where it prints within the box with line breaks and multiple lines if we're printing the doc with a multiline field in its first doc, but if we're printing a combination of docs and one of them had a field with the same name as the multiline field in the later doc but in a single line, when it gets to the later doc it doesn't print it within the box but prints in the vertical middle of the box and truncates at the edge.

Presumably the pseudocode for what I need is something like

```
field[:Multiline] ||= true
```

And I'll go look in the pdf spec right now to see if I can translate that to actual code, but if you know off the top of your head I'd be very grateful.

**Comment by smiller** [comment]
I suspect 

```
field[:Ff] ||= 0
field[:Ff] |= (1 << 22) # multiline
```

might do it, and I'm trying that now for the specific field that we see is showing the behaviour, but I don't know if applying it throughout would cause other fields that shouldn't be multiline to turn multiline.

**Comment by smiller** [comment]
Nope, that doesn't do it.  I'm sorry, I should probably have opened a new issue for this.  Looking at extracting a simple test case into a repo again to make experiments simpler.

**Comment by smiller** [comment]
Test repo at https://github.com/smiller/pdf-form-test-multiline

**Comment by gettalong** [comment]
I think that the way you combine the form fields goes against the spec in this case, e.g. see 12.7.3.2 last paragraph. It essentially says that it is possible to have fields with the same name but only if they have different visual appearance. I guess that having a field being a single-line field and multi-line field goes against this paragraph.

To avoid this problem altogether you should adjust the field names so that they are unique. Then these problems should go away.

And I wanted to say thanks for the good preparation of test cases and problem descriptions - that makes it really easy to jump right in even if the topic is not right at the forefront of my mind :+1:

**Comment by smiller** [comment]
That makes sense.  And since we're only observing this in a single field so far, we can just give that field a different name and preserve the difference that way.   Okay.  Back to being closable, I think.

Thank you very much indeed, again, for your time and your help.  (And the test repos were also useful for me for narrowing the problem scope – totally going to steal that from myself as a diagnostic tool going forward!)

**Comment by gettalong** [comment]
Thanks for your feedback. If there are new developments, just comment on this thread again.
