### ISSUE TITLE
Properly creating custom appearance streams

### ISSUE THREAD

**Issue by kprinssu** [gettalong/hexapdf#90]
I have been playing around with appearance streams for AcroForm fields (Widget Annotations) in order to get it displayed with most PDF viewers. The PDF viewer I am trying to support does not support the catalogue `NeedAppearance` key so I am trying to  recreate the appearance stream that Adobe Acrobat creates.

In order to do so, I have written the following function:

```
# pdf is the HexaPDF::Document
# field is a type of HexaPDF::Type::Annotations::Widget
# font is HexaPDF::Type font
def pdf_create_appearance(pdf, field, font)
  # PDF appearance stream
  ap = field[:AP]

  if ap.nil?
    ap = HexaPDF::Dictionary.new(nil)
    pdf.add(ap)
    field[:AP] = HexaPDF::Reference.new(ap.oid)
  end

  new_n = HexaPDF::Stream.new(nil)
  new_n[:BBox] = [0.0, 0.0, 250.656, 12.96] # constants for now, but represents the width and height of the field

  new_resources = HexaPDF::Dictionary.new(nil)
  new_resources[:Font] = HexaPDF::Reference.new(font.oid)
  new_resources[:ProcSet] = [:PDF, :Text]

  new_n[:Resources] = new_resources
  pdf.add(new_resources)
  pdf.add(new_n)

  ap[:N] = new_n
end
```

I believe that I am close to representing a valid appearance stream but in my above code. The final PDF file contains a stream object that Adobe Acrobat has created but it seems that my above function is not properly writing the Length property (as it is always 0).

Additionally, it seems that the '/Length' is required for PDF viewers to properly render the field value (as I have ruled out the `Resources` key by recreating  only the `N` stream and copying on a working Acrobat created field).

**Comment by gettalong** [comment]
Some pointers:

* You don't need to create dictionaries like you do. HexaPDF ships with pre-defined classes for many PDF types which provide convenience methods. For example, instead of creating a dictionary as resource dictionary, you could do `resources = pdf.add({}, type: :XXResources)`. The resulting object will automatically do some things like setting a default `/ProcSet` value.

   If you only need a simple dictionary, then just use plain old Ruby hashes, i.e `field[:AP] = {}`. They will automatically be converted to Dictionary objects when needed.

* Once an object is added to the PDF document with `pdf.add`, you don't need to store a reference directly. Just assign the object itself and everything will be correctly written, i.e. `field[:AP] = ap`. 

* You create the appearance stream but you don't do anything with it, i.e. there is no contents. What you want to do is `new_n = pdf.add({Type: :XObject, Subtype: :Form}); canvas = new_n.canvas` and then use the canvas to draw something.Otherwise the appearance stream is empty and therefore its length zero.

I'm currently work on adding proper support for AcroForm forms which will make creating appearance streams simple and straightforward.

**Comment by kprinssu** [comment]
That makes perfect sense and the plain old Ruby hashes makes this much easier. It was my assumption that I had to just provide the font for the necessary appearance stream and let the PDF Viewer render the text.

What I did not realise was that I had to actually write data (i.e. the field value) into the stream. Here's a simplified bit of code for anyone interested:

```
# field = ....
ap = field[:AP]
new_nd = pdf.add({Type: :XObject, Subtype: :Form})
# Use field[:Rect] to generate
new_nd[:BBox] = [0.0, 0.0, 250.656, 12.96]
canvas = new_nd.canvas
canvas.font('Times', size: 12)
canvas.text(field[:V], at: [0, 0])
ap[:N] = new_nd
```

**Comment by gettalong** [comment]
@kprinssu Just a heads up: The next version of HexaPDF (tentative release date end of June) will support AcroForm text fields, so if the field already exists and is valid, a simple `field.create_appearance_streams!` will do everything that is necessary to create a visual appearance that is similar to what you would find in e.g. Adobe Reader.
