### ISSUE TITLE
Getting image caption data

### ISSUE THREAD

**Issue by dennyluan** [gettalong/hexapdf#93]
Hey there, this is a great tool! Thanks for making it.

I was wondering if there's a strategy for getting image caption text or information next to or near an image, e.g. something like a "Figure 1" label. Is it correct that the order of image parsing is from top to bottom in the order it appears?

**Comment by gettalong** [comment]
Thanks!

You would need to parse the content stream of the pages to find the image locations and nearby text and then decide whether this text constitutes a caption or not. This task is probably not that easy because captions could appear above, below or besides an image and may not be separated by huge whitespace from other text of the page.

Furthermore, drawing instructions in a content stream of a page may arbitrarily draw anywhere on the page, there is no special order mandated. For example, a PDF creator may first draw all the main text, then the images and then their captions. Or first the images in random order, then the captions from bottom to top and then the text. However, most PDF creators draw content in the reading direction which is top to bottom and left to right for many languages.

**Comment by dennyluan** [comment]
Thanks very much for the response! This is very helpful.
