### ISSUE TITLE
Strange behavior

### ISSUE THREAD

**Issue by matpowel** [gettalong/hexapdf#98]
Firstly, I _love_ this project. Pure Ruby PDF manipulation, clean looking APIs. Super excited, well done everyone.

The big BUT for me is that the couple of PDFs I've tried it on yield super unexpected results, check it out:

``
> hp = HexaPDF::Document.open('in.pdf')
 => ...
> hp.pages.size
 => 4
> hp.pages[0]
 => #<HexaPDF::Type::Page ...> 
> hp.pages.delete_at(0)
 => #<HexaPDF::Type::Page ...> 
> hp.write('out.pdf')
Traceback: ...
HexaPDF::Error (Validation error for (8,0): Required field Parent is not set)
``

Also for a 4 page PDF, using the CLI when trying to split a PDF has the following weird behavior:
- hexapdf modify --force in.pdf -i 2,3 out.pdf
  - produces a 2 page PDF (correct) but both pages are totally blank
- hexapdf split in.pdf
  - correctly splits the PDF into 4 single page PDFs!

I can't post the PDF I tried because it's a client bill but I believe all 4 pages are images.

UPDATE: 
I PDF'd the wsj.com homepage so I'd have a vector PDF with a combination of images and text and I got the same outcome using the Ruby console but this time the CLI modify tool worked as expected.

What is the status of this project? Is it anywhere near production ready? I'm not sure how much time I can apply to helping right now but if our team adopts this project we can try set some time aside to helping.

Thanks.

**Comment by gettalong** [comment]
First of all, thank for the commendation!

As for the first problem, please have a look at the documentation of [HexaPDF::Document::Pages#delete_at](https://hexapdf.gettalong.org/documentation/reference/api/HexaPDF/Document/Pages.html#method-i-delete_at). It states that the page will be deleted from the page tree but *not* from the PDF itself. Internally [HexaPDF::Type::PageTreeNode#delete_page](https://hexapdf.gettalong.org/documentation/reference/api/HexaPDF/Type/PageTreeNode.html#method-i-delete_page) is used (I will add a "see also" reference) where it is stated that the Parent field is set to `nil` which causes this validation error.

Maybe it would be better to also delete it from the PDF document itself (since the object is returned one could then always re-add it to the document), will have to think about it. To remedy the validation error, do something like this:

~~~ ruby
hp.delete(hp.pages.delete_at(0))
~~~

It would help to get a look at the PDFs in question. If they are confidential, you could send me one to info@gettalong.at. Otherwise running "hexapdf ins in.pdf r" and providing the result would probably also help (this should not reveal any confidential information as no page contents are included).

The `hexapdf modify` and `hexapdf split` tools are implemented in different ways to account for their needed functionality. If `split` works but `modify` not, there may be a bug in `HexaPDF::Type::Page#copy_inherited_values`, especially if each page only consists of a single image. As mentioned having access to a problematic PDF greatly helps in determining the exact problem.

Yes, I think that HexaPDF is production ready albeit the whole PDF functionality is not yet implemented. The commercial version is used by companies around the world. The library is very stable, fast and well tested. The main core functionality will probably not change much, most of the changes are implementations of missing PDF functionality.

If you'd like, send me an email to info@gettalong.at with information on what you want to do with HexaPDF so that I can tell you whether and how it is possible with the current version.

**Comment by matpowel** [comment]
@gettalong thanks so much for the response, this indeed the problem. I haven't read into the library enough to know why one would want to remove a page from the document but keep it in the page tree, or vice versa, but this definitely solved my issue. If there are no use cases for the two being out of sync, perhaps deleting from one should automatically delete from the other?

Regarding the modify vs split behavior, I will create a multi page PDF with only an image for each page (like most mobile phone app scanners would create) and test against that when I get a second later today.

For now we've got a basic way to pull pages out of a document and re-save it!

**Comment by gettalong** [comment]
@matpowel I have updated the page deletion code so that deleting a page now deletes it from the page tree and the document. I thought about use cases where a deleted page would be re-added but couldn't think of any. So the various page-delete methods now just delete the page and don't return anything.

As for the problem with the CLI: It would be great if you could provide a test PDF so that I can find the problem!

**Comment by matpowel** [comment]
@gettalong sorry I didn't reply earlier, we had to focus on a couple of other major areas of the code.

What's funny about this is that we ended up using the lack of document deletion in our page move method. We've now modified it per below, but I still think the new idiom is much nicer. Other parts of our code are cleaner and more intuitive when a delete is what is wanted.

<img width="509" alt="image" src="https://user-images.githubusercontent.com/124018/96315636-f3ef6280-0fd3-11eb-9e79-4a574dba417c.png">

Unfortunately it's very hard for me to ever send you the test documents because we deal with customer financial documents and they are almost always sensitive. I'll hopefully get one that I can send at some point.

**Comment by gettalong** [comment]
@matpowel No problem - thanks for the feedback! I will add "move page method" to my TODO list ;)

As for sensitive PDFs: If it would help, I could sign a confidentiality agreement concerning the PDFs.

**Comment by gettalong** [comment]
@matpowel FYI I have just implemented the page moving method - see https://github.com/gettalong/hexapdf/commit/38b62bf12db5757f72091770fc2352762598e51f

Since I can't really do anything with respect to the modify/split problem, I will close this issue for now. If you have some more information that could help with this, I will re-open it for further investigation.
